### ISSUE TITLE
Debug screen output and maybe input options

### ISSUE THREAD

**Issue by CigamPower** [GodotVR/godot-xr-tools#114]
The current debug screen is nice and shows player position and such. However for developing on the quest 2 I needed to see what certain variables were at. So I tweaked a text label in a similar setup, and got help from people to use a singleton logic to pass variables to it. Then in game I can see outputs of stuff I am working on.

Overall it would be nice to have some kind of easy to pass variable screen for like a dump of values, or tracking specific values, etc. My current version just scrolls to the bottom when new stuff is added, but it would be interesting to have that when aiming/pointing the joystick on that controller could scroll the window. Or allow for tabs or buttons to select or change values on the fly in game. To prototype and debug issues faster without having to rebuild the game to the quest. If that were to be done it might be having to implement some input prompt or keyboard, but that would get complicated too.

Having some way to pass variables though is mainly what I have been using a tweaked version of this to do, but would be neat to see some other features that people might need for debugging.

**Comment by BastiaanOlij** [comment]
An initial implementation was added into the "wrist UI" in PR #496. If there is any further information that should be added to this, please open a specific issue or submit a PR with the information added to the existing UI.
