### ISSUE TITLE
Feature Request: Separate Turning from Direct Movement Function

### ISSUE THREAD

**Issue by teddybear082** [GodotVR/godot-xr-tools#115]
There is a control convention where direct or teleport movement is located on the dominant hand along with strafing (which present XR-tools supports) but then the off hand just has snap or smooth turning and can utilize the Y axis up /down for non-movement in-game controls, like quick switching between weapons, or jumping and crouching.  This is fairly trivial to hack with the current tools by copying the direct movement scene and script and scraping out anything related to direct movement but it would be good to officially have its own module so people could mix and match, similar to what has now been done with separating out flight movement from direct movement.

My hacked files are here for turn only: https://drive.google.com/drive/folders/1osoVU7tWHyNJwMDtK8jpxOt9aVN4Rsgb?usp=sharing

**Comment by Malcolmnixon** [comment]
I've got a pull request implementing this change and also added it to https://github.com/Malcolmnixon/godot-xr-tools-demo.

**Comment by teddybear082** [comment]
I think we can close this issue now right?

**Comment by Malcolmnixon** [comment]
I think this one has had enough testing, so yes we can close it.
