### ISSUE TITLE
Feature Request - Crouch Function

### ISSUE THREAD

**Issue by teddybear082** [GodotVR/godot-xr-tools#116]
Presently it appears room scale crouching is supported but button crouch is not an official function.

**Comment by Malcolmnixon** [comment]
This goes quite nicely with some other features we've been thinking of which control the players body, including:
 - height calibration (for tall players and people in wheel chairs)
 - shrinking the player height while climbing to allow for pulling the body on to the top of buildings.

**Comment by teddybear082** [comment]
@Malcolmnixon I have an alpha version of getting climbing to the top of platforms and buildings working by adding / replacing this code to the climbing function after the code where you have the average offset for left and right hands combined.  Does this approach make sense to you?

https://pastebin.com/PFT5ESrz

**Comment by teddybear082** [comment]
@Malcolmnixon is your controller suffering from drift or something else? If its broken due to drift I have found that compressed air and electronic contact cleaner (mine is CRC Mass Air Flow Sensor Cleaner) work wonders.

**Comment by Malcolmnixon** [comment]
Could you check out the crouch functionality in the latest https://github.com/Malcolmnixon/godot-xr-tools-demo and let me know if it works for you?

**Comment by teddybear082** [comment]
This works!! Nice work! I couldn't figure how to do this no matter how hard I thought about it and tried.
