### ISSUE TITLE
Movement providers should have a means of sharing state information

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#120]
Movement providers should have a means of storing state information in a central location when there may be multiple instances of the providers. For example:
 * Function_Direct_movement instances (on each controller) may want to share an "is_sprinting" state
 * Function_Jump_movement instances (on each controller) and the Function_JumpDetect_movement instance may want to share a jump-cooldown timer

Currently some of this information has been dumped into the PlayerBody instance, but such an approach is not modular.

**Comment by BastiaanOlij** [comment]
After discussing with Malcolm, we solved this differently and this is no longer an issue.
