### ISSUE TITLE
Update the front page wiki instructions to account for FPController scene

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#125]
I'm being caught out by some inconsistent documentation, where the setup page on this toolkit still references ARVROrigin instead of FPController.  https://github.com/GodotVR/godot-xr-tools/wiki#setup

There's also a different set of instructions in the mainline docs, referring to the FPController under the openxr plugin.  
https://docs.godotengine.org/en/stable/tutorials/vr/openxr/index.html

(In fact the border between the open between the openxr and xr-tools feels muddled.  It looks like FPController belongs on the latter, not the former as it is pure GDScript.)

I doubt I can constructively edit these instructions as I don't exactly know where things are going.  There seem to be duplicate ARVRControllers nodes (for controllers and aim systems) which feels like something is in transition.
![image](https://user-images.githubusercontent.com/677254/166718905-118eab44-1a6a-4945-968e-ed9e6e208a08.png)

**Comment by BastiaanOlij** [comment]
This is on purpose @goatchurchprime , `FPController` is a node specific to the OpenXR plugin, we're trying to keep XR-tools platform agnostic so wherever possible I try to keep the documentation such that it assumes nothing is coming from the plugin being used.

**Comment by goatchurchprime** [comment]
Is this not very theoretical?  I thought OpenXR is going to be the only thing around.  Nevertheless I got badly caught out.  Maybe a good compromise is to write at the start of this section of the wiki: "if you are using only OpenXR, you may want to skip ahead by using the FPController scene".

**Comment by BastiaanOlij** [comment]
It would be great if we end up with OpenXR as the only required interface but there are still plenty of platforms that aren't jumping on the bandwagon. Right now the only one of those we support is ARKit I guess but still...

**Comment by BastiaanOlij** [comment]
Godot XR Tools now has the whole staging setup, start xr scripts and demo projects that provide a cross platform solution.

More information is available on https://godotvr.github.io/godot-xr-tools/

Closing this issue.
