### ISSUE TITLE
Virtual Holster Object For Testing / Feedback

### ISSUE THREAD

**Issue by teddybear082** [GodotVR/godot-xr-tools#127]
I made a virtual holster object that in theory can be placed anywhere in the scene, assigned a pickable object scene to be its "holster object", and assigned buttons for left and right hands to put items in and out of the holster.  It appears to work regardless of whether the pickable items have the hold to grab or reset transform options set (or combinations thereof).  This could be used to create body holsters or (although I haven't tried yet) possibly nested to create a rudimentary "backpack inventory" system.  The holster emits a signal when an item is taken out or put back in.  If the user does not have a signal-based script system for handling sounds, they can assign a sound for this by clicking on editable children and assigning a holster sound to the AudioStreamPlayer3D.

Link here (the holster.gd and holster.tscn files) for testing and consideration for possible inclusion as one of the "object" assets for XR-Tools (though right now I have the path set as still being in "functions"): https://drive.google.com/drive/folders/1osoVU7tWHyNJwMDtK8jpxOt9aVN4Rsgb

You just have to adjust the area position and collision shape size to your preference (which can take some trial and error if putting it on the player body).

**Comment by teddybear082** [comment]
Cool! I also finally figured out how to use Github and have a repository now so if there is a best way in the future for me to be helpful let me know.  I like feeling like I am helping but understand I am a total beginner so don't want to make your job harder either.

**Comment by teddybear082** [comment]
I liked your video on snap zones so closing this issue!

**Comment by Malcolmnixon** [comment]
Snap-zones in other frameworks tend to grow a bunch of features such as grab-cloning, or return-to-snap. My plan is to get the basic snap-zone in place, and then improve it iteratively through feature-requests.
