### ISSUE TITLE
Is it supporting HTML5?

### ISSUE THREAD

**Issue by Atem1995** [GodotVR/godot-xr-tools#128]

**Comment by Malcolmnixon** [comment]
The godot_xr_tools project is just some helper classes that work with an ARVR provider library such as godot_openxr (https://github.com/GodotVR/godot_openxr). I don't believe godot_openxr supports WebXR.

There's an article at https://www.snopekgames.com/tutorial/2020/how-make-vr-game-webxr-godot which explains how to build for webxr, and it uses the same ARVROrigin, ARVRCamera, and ARVRController that godot_xr_tools makes use of; so it has a good chance of working.

**Comment by teddybear082** [comment]
XR Tools does work with HTML5 provided you also use the openxr asset as well as the instructions malcolm linked. A brief example can be found here: https://github.com/teddybear082/Godot-WebXR-Avatar-Test

With a playable demo here: https://teddybear082.itch.io/godot-webxr-avatar-test

**Comment by lunarcloud** [comment]
Perhaps a WebXR export should be included as a demo in the project?

**Comment by dsnopek** [comment]
WebXR support was recently merged! I think this can be closed :-)
