### ISSUE TITLE
Feature Request - Snap Zones

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#129]
Pickable objects should support being "snapped" into snap-zones. These snap-zones should support being fixed to the environment, or put on the player as pockets.

**Comment by teddybear082** [comment]
I liked your video on this! I closed my "holster" issue accordingly.  Not sure if it is in your code but would be good to have a check box in the editor to say whether the object should be hidden or not when placed in the snap zone, e.g., difference between using the snap zone on a "back pack" object that hides it, or using the snap zone on a shoulder holster where you want other players to continue to see the object on your back, like a sword.

**Comment by Malcolmnixon** [comment]
Tested in 2.4 release.
