### ISSUE TITLE
Pickup fails to find closest object

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#131]
The Function_pickup attempts to find the closest object that can be picked up. This code has two issues.

Firstly there is no method to find the distance from the hand to the "closest part" of the object, so it uses the distance to the "origin/center" of the object. This works reasonably well for small objects, but can produce unexpwcted results with larger objects.

The second issue is because the distance to the objects center is calculated, the numerical distance can be quite large if the object is a sky-scraper the player is attempting to grab for climbing. The Function_pickup routine uses a distance-square lookup, but the starting value MAX_GRAB_DISTANCE2 is 1000, which corresponds to a distance of only 32 meters. If the skyscraper is 100 meters tall then the center can be 50 meters away and the search fails.

The solution would be to increase MAX_GRAB_DISTANCE2 to a larger value such as 1000^2 or 1,000,000.

**Comment by BastiaanOlij** [comment]
Interesting problem. We need to be careful we don't overload the logic and slow things down, yeah, we may need to do a raycast to each object within range so find out how close it is.

Wonder if there are any functions directly on the physics server that will give us this info so we can keep the expense down.

**Comment by BastiaanOlij** [comment]
Btw, I think any setting should be in meters, if we need to square the number we should calculate an internal variable as the square of it.

Maybe overkill with constants, but definitely for user settable properties.

**Comment by Malcolmnixon** [comment]
Tested and verified fix with 0d5ebbf349137709f30f2cffe6cdd18ea4ce881c version.
