### ISSUE TITLE
For consideration - "Bullet Time" Module

### ISSUE THREAD

**Issue by teddybear082** [GodotVR/godot-xr-tools#132]
Hi all, for your consideration, a customizable "bullet time" module here:  https://github.com/teddybear082/Godot_XR_Tools_Bullet_Time/tree/main/addons/godot-xr-tools/functions

It is pretty fun to use bullet time when combined with the grapple function to pinpoint grapple targets, when jumping between platforms, or when used with S.Y.M.B.I.O.T.E.'s mesh slicer to carve up objects in slo mo.

One improvement (I'm sure there are others) could be allowing the user to choose between "matrix" and "superhot" style slo-mo as a top-level option in the editor.  Matrix being everything goes slo-mo for a period of time (current implementation), Superhot being "time only moves when you move."  I think that would involve maybe setting the time scale to some combination of the player body velocity, controller velocity and camera velocity, have to think about it more.  Garbaj has a very simple version of setting time scale to something very tiny like .02 when the player's velocity is zero but I don't think that would work well in VR since hands and head can also move, not just the player's body.

**Comment by Henodude** [comment]
I feel like this should be separate from this repository. Still cool though.
