### ISSUE TITLE
For consideration - Jog in Place Locomotion

### ISSUE THREAD

**Issue by teddybear082** [GodotVR/godot-xr-tools#134]
I ported over as best as I can Neosparks' jog-in-place locomotion module to the OpenXR-Tools style.  Code can be found here: https://github.com/teddybear082/Godot_XR_JogInPlace_Locomotion

**Comment by Henodude** [comment]
I think that it would also be good to have an option to use this for sprinting (i.e. walk with the joystick and jog in place to move faster). Just a thought.
