### ISSUE TITLE
Feature request: Multiple point object interaction

### ISSUE THREAD

**Issue by Henodude** [GodotVR/godot-xr-tools#135]
Right now, you can only hold an object at one point. I think it would be useful to have multiple points to grab an object. This would allow for more complex object interactions. My vision for this feature includes includes the following:
- You can hold an object from any one of the points. 
- You can hold an object from multiple points. 
- Certain points can't be grabbed by the player and controlled with code.
- Each point has a value to determine how much of an influence it has. 

Let me know if any of this is unclear, and I can help clear it up.

**Comment by Malcolmnixon** [comment]
There's a reset_transform_on_pickup option on packable objects which let's you hold it by wherever the hand was when it was grabbed (referred to as precise-grabbing in some frameworks).

I agree there should be options for multiple grab points, and in addition they should support overriding the hand poses. Consider holding a gun by the barrel or the grip would have different poses.

**Comment by DigitalN8m4r3** [comment]
since the op was asking for multiple grabpoints and we thands to @Malcolmnixon got those now
i would suggest markin this as complete

the following sound alot game specific
*Certain points can't be grabbed by the player and controlled with code.
(what has this then to do with grab points?)
*Each point has a value to determine how much of an influence it has.

**Comment by DigitalN8m4r3** [comment]
this would be more useful to be implemented as a line grab for Melee Weapons and long items. 

Where u you grab point A with lets say the left hand and if u keep the trigger pressed and let go off the grip it slides down towards point B.
Once u press gripp while holding down trigger it could lock the location of hand grabpoint.

**Comment by Malcolmnixon** [comment]
Ok, I was thinking it of enhancing it such that a single hand could hold the same pickable by different "handles". However it's challenging even thinking of a good example do perhaps it's use would be limited.

As such I think this is complete. We'll work on the two-handed grabbing as a separate item.
