### ISSUE TITLE
Bug - Enabled = false not deactivating movement providers in XRTools 2.4

### ISSUE THREAD

**Issue by teddybear082** [GodotVR/godot-xr-tools#139]
Steps to reproduce:

Use Master OpenXR asset
Use XR-Tools latest release 2.4
Add direct movement nodes as children of left and right controllers
Check the box to make enabled = false in one of the direct movement nodes
Start scene
Regardless of the enabled checkbox being false on one of the direct movement nodes, both joysticks will still create direct movement

Also impacts (at minimum): Turn function, jump function

I'm wondering if the addition of the "is_active" property somehow undid the ability to disable movement providers by unchecking the enabled box in the editor? Note, using [function].enabled = false in code also fails to disable these movement providers, so it isn't just an editor issue.

Confirmed that disabling providers in editor or through code worked fine in 2.3.

Should we have a line in these providers for "if enabled = false: return"?  Or is it more complicated than that with the new "is_active" setting?

**Comment by Malcolmnixon** [comment]
@teddybear082 could you verify this change works with your project and close the issue if it's good for you?

**Comment by teddybear082** [comment]
Yes this works thank you! Closing!
