### ISSUE TITLE
Feature Request - Add moving target support to grapple hook

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#147]
Currently the grapple hook captures the global world coordinates where the grapple was fired. Instead the grapple hook should use relative coordinates from the target object. This would allow the grapple to follow the target if it moves.

**Comment by teddybear082** [comment]
Nice I never even really thought of moving targets!

**Comment by Malcolmnixon** [comment]
Grappling moving targets working in demo project.
