### ISSUE TITLE
Feature request: object teleport block

### ISSUE THREAD

**Issue by 0968128** [GodotVR/godot-xr-tools#156]
Is there already an option to make it impossible to teleport onto certain objects? Not just place it on a different layer, so the teleporter goes through, but an option to actually block the ray and make it red.

**Comment by Malcolmnixon** [comment]
You may want to check out the pull request and see if it achieves what you're after. With this the Function_Teleport now has a Valid Teleport Mask which specifies the object layers where the teleport is permitted.
![image](https://user-images.githubusercontent.com/1863707/176801174-b9a75bef-a799-4703-ab47-0261a7c441f9.png)
The default value of this new property is "everything", so existing projects should not be broken.

**Comment by Malcolmnixon** [comment]
This was tested in the teleport demo of https://github.com/Malcolmnixon/godot-xr-tools-demo by preventing teleporting onto the rotating carousel.
