### ISSUE TITLE
Add bouncy property to physics

### ISSUE THREAD

**Issue by GammaGames** [GodotVR/godot-xr-tools#170]
To make the player ricochet off stuff, because that's a good idea in VR

**Comment by Malcolmnixon** [comment]
@GammaGames could you check out the branch and let me know if it's doing what you want. You can also play with the latest https://github.com/Malcolmnixon/godot-xr-tools-demo which has a few trampolines (purple plates) scattered around - the ones beside the climb-building are sloped so you can test angled-collision bounces.

Note: this only works if the movement is being performed by the PlayerBody. It won't be applied if an exclusive movement-provider (such as the grappling hook) has taken over physics.

**Comment by GammaGames** [comment]
You're fast, I'll try to check it out tomorrow! Thanks!

**Comment by GammaGames** [comment]
I played around with the demo, looks good!
