### ISSUE TITLE
enable teleportation with ramps

### ISSUE THREAD

**Issue by meigel** [GodotVR/godot-xr-tools#19]
Current implementation seems to only allow teleportation onto flat plane. Would be nice to allow for slopes so that ramps can be used.

**Comment by BastiaanOlij** [comment]
Hmm, I have to look into that, it indeed checks for horizontal planes so you don't teleport onto a wall but we could compare the normal to the up vector to allow teleporting on slopes

**Comment by BastiaanOlij** [comment]
Fixed in #32, there is now a Max Slope property
