### ISSUE TITLE
Rumble Should be Added to Standard Functions

### ISSUE THREAD

**Issue by lunarcloud** [GodotVR/godot-xr-tools#191]
The idea is that an enable-able, configurable-intense rumble should be added to things across the tools.

Examples:
- hand is in range of pickable
- hand collides
- flying (to simulate jetpack or the like)
- grapple shoot/attach
- on landing a fall
- on jumping

I intend to work on this now that #40 / #190 are merged

**Comment by BastiaanOlij** [comment]
Owh these would be nice additions for sure!

**Comment by lunarcloud** [comment]
Note to self, in pseudocode:

```gdscript
dictionary<event_name: string, { magnitude: float, hands: Hands, remaining_secs: float, pausable: bool }>

set(event_name: string, magnitude: float, hand := Hands.Both, duration := -1.0, pausable := true) -> void
    // todo add to the dictionary

_process(delta: float) -> void:
    // todo rumble value for each hand is the highest magnitude for that hand
    // if paused, filter out (pausable == false)
    // if nothing, reset rumble for the hand to 0
```

**Comment by lunarcloud** [comment]
Maybe provide a helper method for folks, like myself, that are writing a game that does both xr and normal - to convert the magnitude from the standard input system rumble's weak/strong magnitudes into a single one.

```gdscript

combine_magnitudes(weak: float, strong: float) -> float:
    if strong > 0.001:
        return 0.5 + clamp(strong/2, 0.0, 0.5)
    else:
        return clamp(weak/2, 0.0, 0.5)

```

**Comment by lunarcloud** [comment]
Starting work over at [lunarcloud:feature/191_rumble ](https://github.com/lunarcloud/godot-xr-tools/tree/feature/191_rumble )

**Comment by lunarcloud** [comment]
Seems like the Godot4 rumble may be https://docs.godotengine.org/en/latest/classes/class_xrnode3d.html?highlight=XRNode3D#class-xrnode3d-method-trigger-haptic-pulse but the docs on this API is not great

**Comment by lunarcloud** [comment]
Discussed with @Malcolmnixon , we should wait for Godot XR Tools 4.3.x development to start, as using the new static variable syntax will simplify the implementation greatly for rumble-generating nodes finding the rumble manager.

**Comment by lunarcloud** [comment]
working on the code in a godot 4 branch. Demo progressing...

https://github.com/lunarcloud/godot-xr-tools/tree/feature/191_godot4_rumble

![image](https://github.com/GodotVR/godot-xr-tools/assets/1565970/95fffef5-d55d-43ae-b07a-3edc60cb2df6)
