### ISSUE TITLE
Function_crouch: add a toggle feature rather than just hold and crouch feature

### ISSUE THREAD

**Issue by teddybear082** [GodotVR/godot-xr-tools#203]
Just making this issue as a placeholder.  This is already implemented in the godot-xr-avatar repo here:

https://github.com/Godot-Dojo/Godot-XR-The-Dojo/blob/main/addons/godot-xr-tools/functions/Function_Crouch_movement.gd

So once XR Tools 3 is out and stable I can submit a pull request for this change.

**Comment by BastiaanOlij** [comment]
Sweet!

**Comment by Malcolmnixon** [comment]
@teddybear082 could you confirm this works as desired, and if so close the issue.

**Comment by teddybear082** [comment]
This is perfect thanks! (Tested in TPS demo project, works well).
