### ISSUE TITLE
New find node script in ARVRHelpers may be broken with custom XRTools classes

### ISSUE THREAD

**Issue by teddybear082** [GodotVR/godot-xr-tools#263]
I think the "is_class" function does not work to return custom class names.

I tested when creating my sprint movement functions, adding the code to search for direct movement providers repeatedly crashed the editor.  When moving that code to the process function so that it would at least run, the errors came from the new _find_child script. According to documentation, is_class will return true only for the base Godot class not any custom classes.  There is an "is" keyword, i.e., if node is class_name, but I'm not sure if this works either in the expected way; I couldn't test because "type" is locked to a String type variable and if is keyword works, the class name would be just a class name and not a string (I think).

**Comment by Malcolmnixon** [comment]
Yah, apparently this is a common issue with gdscript. The best solution appears to be overriding is_class in all classes. Something like:

```gdscript
func is_class(name : String) -> bool:
    return name == "CustomClass" or .is_class(name)
```

**Comment by teddybear082** [comment]
Also instead of overwriting is_class in every XRTools function, maybe you could utilize the Node "get_filename()" method instead.  E.g., in lines like 145 of ARVRHelpers, you could use if node.get_filename() == type instead of node.is_class(type)), and in the function that is calling this, type could be a string maybe of the absolute path to the script for the relevant XRTools function, e.g.,

ARVRHelpers.find_child(_left_controller, "*", "res://addons/godot-xr-tools/functions/movement_direct.tscn") 

I think this would allow you to keep "type" as a String, just it would have to be documented that to use the function you need to drag over the path to the XRTools functions you are searching for.  Not sure if that would work but just an idea.

**Comment by Malcolmnixon** [comment]
I'm trying to model these functions on the new Godot 4 find_children() method so I'd like to keep the contract essentially identical, however there too it looks like custom classes isn't supported - at least not until https://github.com/godotengine/godot/pull/62273 goes in.

Until the standard *::is_class() recognizes class_name, the only option appears to be to manually add it.

**Comment by Malcolmnixon** [comment]
According to https://github.com/godotengine/godot/issues/21789#issuecomment-1312540449 it looks like even the workaround of overriding is_class() is not supported in Godot 4. As the project is trying to simultaneously support Godot 3 and Godot 4 with minimal differences, it seems like the advanced node-search capability can't be supported yet.

I think for now it's best we stick with the user manually specifying NodePath properties to the appropriate nodes. It's a shame as this results in significantly more manual configuration steps.

**Comment by Malcolmnixon** [comment]
Bastiaan decided he wanted them in to simplify the code. It'll either be fixed shortly in Godot 4, or when I port it over I'll do a temporary tweak to make it work until they get around to fixing it.

**Comment by Malcolmnixon** [comment]
This works fairly well, with the one caveat that the is_class() override only works in the editor if the script is also marked as a tool script.
