### ISSUE TITLE
little confused with godot 4 and VR

### ISSUE THREAD

**Issue by flobotics** [GodotVR/godot-xr-tools#265]
hi,
i installed Godot_v4.0-beta4_win64 , then i git cloned https://github.com/GodotVR/godot-xr-tools.git , switched branch to "4.0-dev" and copied the folder addons/ into my godot-project-folder.

I activated the Godot XR extension in Project->project-settings->extensions and activated the XR->Shader.

After adding XROrigin3d, XRController3d ,xrcamera and added Common_Shader_Cache.tscn as child scene with some boxmeshes to the scene, i press play-button and a black window pops up ? Thats it, no picture in VR Headsets (HP reverb G2, pico 3, pico 4) ?

In the debug console it prints: E 0:00:00:0041   create_instance: OpenXR: OpenXR Runtime does not support XR_KHR_vulkan_enable2 extension!

Confused: I dont need https://github.com/GodotVR/godot_openxr.git anymore, because its build into the core ? or ?

Where/How can i choose the VR devices , or do i not need this anymore ?

thx for help

**Comment by flobotics** [comment]
ahh, i forgot the DirectionalLight3D  , then the pop-up window is not black anymore and i can see the scene. I follow this https://www.youtube.com/watch?v=wDXnsy2IH1A   video.

But i cannot move, also it does not start/show anything on e.g. HP reverb G2 which is connected to the windows pc ?

**Comment by flobotics** [comment]
i got it to build android for pico 4. But when i start the application from the editor with the android-icon on the top-right-corner of the editor. It deploys the apk onto the device and starts it, but it only starts it in "cinema-mode" ( just a screen infront of you)  and its not possible to move the head or anything ? 

 Failed loading resource: res://addons/godot-xr-tools/staging/loading_screen.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/export/editor_export_platform.cpp:712 - Condition "ps.is_null()" is true. Returning: p_path
  Transient parent has another exclusive child.
  Transient parent has another exclusive child.
Installing to device (please wait...): Pico A8110

**Comment by flobotics** [comment]
if you use HP reverb g2 and got the error:

 create_instance: OpenXR: OpenXR Runtime does not support XR_KHR_vulkan_enable2 extension!

Open steamvr->settings  enable-extended-settings, then in Developer-section, change "actual openxr runtime" to steamvr (from windows mixed reality)

after that, i dont get the error anymore

**Comment by BastiaanOlij** [comment]
WMR indeed has the annoying habit of only supporting DirectX, so us poor OpenGL and Vulkan guys just have a non working system unless the user manually switches the OpenXR runtime over to steamvr. Sucks but its the way it is.

A directX backend is coming to Godot 4 soon, so hopefully we can make WMR work in due time.

**Comment by peteristhegreat** [comment]
Here's one approach for switching the runtime quickly:

https://www.reddit.com/r/oculus/comments/jf11f8/comment/i5lsdsb/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

https://github.com/WaGi-Coding/OpenXR-Runtime-Switcher/releases

It appears to do a regedit and detect the current settings.
