### ISSUE TITLE
Implement hand-pose area to override hand poses

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#268]
With the new hand-poses support, a new XRToolsHandPoseArea should be added to support setting the poses when the hands enter an area.

**Comment by DigitalN8m4r3** [comment]
Indeed this is goin to be useful, especialy considering stuff such as door handles etc. 

it might be a good idea to add a check to exclude a finger - thumb/Index..etc. only

as this might allow to perform some stuff on button press on the desired finger
