### ISSUE TITLE
XRButtons

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot-xr-tools#272]
in `interactible_area_button.gd` there is an error
![obraz](https://user-images.githubusercontent.com/51274570/202264015-4f967c73-b8c0-47f0-bd67-2dee73bbe176.png)
There should be
![obraz](https://user-images.githubusercontent.com/51274570/202264080-92876e25-146f-4284-89a5-5db3d800d47b.png)

otherwise script crashes game

**Comment by BastiaanOlij** [comment]
Indeed, signal is defined to receive the button as a parameter. @pietru2004 happy to accept a PR with the fix, else I'll leave it to @Malcolmnixon to pick this up when he has a free minute :)

**Comment by pietru2004** [comment]
If he won't have free minute before me then I will send PR. 

Side Note: ATM it is bit late for me.
