### ISSUE TITLE
ray interactor

### ISSUE THREAD

**Issue by flobotics** [GodotVR/godot-xr-tools#279]
hi,
is there a ray interactor ?  is there a way to implement e.g. text-input and button ui into 3d and interact with it ?

can not find info on net

thx

**Comment by BastiaanOlij** [comment]
@flobotics this is standard functionality in Godot. Note that we have a pointer function script that uses a raycast on the controller and can interact with any physics object. 

Have a look at the `interactable_area.tscn` and `interactable_body.tscn` scenes, you can inherit those and created objects that react to the raycast.

At the moment we only support UIs through `Viewport_2d_in_3d.tscn`, but at some point creating pure 3D UI elements is a thing we want to look into. We'll have to raise the minimum version of Godot to 3.5 as in 3.5 Label3D was introduced.

**Comment by flobotics** [comment]
ah pointer function.  I use godot 4. 

thx
