### ISSUE TITLE
Oculus Quest controllers not tracking correctly.

### ISSUE THREAD

**Issue by reconlap** [GodotVR/godot-xr-tools#31]
Created a simple app using Godot v.3.2.beta1, godot-xr-tools 2.0 and OVRMobile ARVRServer. The app loads fine on the Quest ( v17.0.0.244) , headset tracks but the controllers are frozen, they will rotate when you press the trigger but wont track hand movements.

Regards

**Comment by reconlap** [comment]
After more poking around it appears xr-tools is treating the quest controllers as Oculus Go controllers.

**Comment by BastiaanOlij** [comment]
Sorry for the late reply, I get too many updates from GitHub it's easy to miss things.

The godot-xr-tools library has no influence on this, it is the ARVRController nodes that are tracked and that is fully controlled by the plugin you use. Have you set the 6DOF mode in the Android export settings?

**Comment by reconlap** [comment]
Hi, 
  Thx for the reply, Don't worry about the delay, just glad I got one. 

  You are correct, I had not set 6DOF in the Android export setting dialog. It all started working as soon as I set that. I'll be closing this ticket now.

  Thanks for your help and all your work on VR.

Regards
