### ISSUE TITLE
Input Problems

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot-xr-tools#313]
Diffrent controlers have diffrent buttons. I see it problematic cause I can't be sure what inputs will be where on diffrent controlers. Example - Hp reverb gen headset 1 controler has touchpad but it launches only inputs 11(ontouch) and 13(onpress), while there is place for at least 4 more inputs.

**Comment by BastiaanOlij** [comment]
This is something solved in Godot 4 where we have control over the action map.

This is also not an issue for our XR tools library but due to the fixed input map used in Godot 3.

**Comment by pietru2004** [comment]
so if I copy 4.0 branch and make VR game with cur stable bate of gd 4 then it should be not an issue ?
_I know it might be unstable_

**Comment by pietru2004** [comment]
I just coppied the 4.0-dev branch and am like... 
you mother hackers
![obraz](https://user-images.githubusercontent.com/51274570/211200602-28d684fc-a76e-414c-bf86-b8598581140b.png)
