### ISSUE TITLE
Poke feature lags behind the finger tip by one physics frame

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#328]
The poke feature works pretty well, but the way that it lags behind the fingertip when you move your hand really bugs me.  This might be too hard to fix it for now, but I'm logging this as an issue so anyone else who is bothered by it knows what fix attempts won't work.

First I tried using a PinJoint connected between a static object in Poke and the PokeBody.  This should be the way it is implemented, but the Godot physics for PinJoints is terrible in that it works like a sloppy rubber band even in free space.  It seems an `_integrate_forces()` function is defined in PokeBody to implement what the PinJoint should have been doing.

Then I tried a `move_and_collide()` in a `_physics_process()`, and the the poke body was still laggy.  (This should work because it moves it to the position if there is no collision.) Even setting `global_transform.origin = get_parent().global_transform.origin` in a `PokeBody._physics_process()` is laggy.  In fact the PokeBody is only coincident when you set the transform.origin in the `_process()` function.

Obviously, when you set the transform every other process frame (or every three frames) you get a double (or triple) image for the PokeBody, once on the fingertip and once one frame behind.  (It's not possible to screenshot this effect for illustration.)

```GDScript
var n = 0
func _process(delta):
	n += 1
	if (n%2) == 0:
		global_transform.origin = get_parent().global_transform.origin
```

Here's what's really strange: The PhysicsFrame runs at 1/3 the rate of the image frames (20Hz vs 60Hz).  So why don't we get a triple image of the PokeBody when we set the transform.origin in the _physics_frame()?

Aside from this mystery, the only way I can imagine fixing this issue is by faking it: Set the PokeBody/MeshInstance position in the _process() function unless a collision has been detected.

**Comment by Malcolmnixon** [comment]
I've been considering an equivalent workaround for the physics hands when we get to the. - for the same lag reasons

**Comment by BastiaanOlij** [comment]
This should work correctly in Godot 4.

The problem in Godot 3 is that `_physics_process` runs before `_process` and it is within `_process` where we (re)position the controller node. Even in `_process` it isn't until the process of the ARVRController node runs that it is updated in which case it's possible the physics hands or poke nodes `_process` has already been run.

In Godot 4 repositioning is handled before physics runs (unless if you run physics in a separate process in which case nothing will save you).

One possible workaround would be is to not use the transform of the [ARVRController](https://docs.godotengine.org/en/stable/classes/class_arvrcontroller.html) node but instead access the [ARVRPositionalTracker](https://docs.godotengine.org/en/stable/classes/class_arvrpositionaltracker.html) directly which has already been updated. Unfortunately we don't seem to expose `ARVRServer::find_by_type_and_id` so you'd need to loop through them to find the correct one.

So something like:
```
func _physics_process(delta):
    for i in ARVRServer.get_tracker_count():
        var tracker = ARVRServer.get_tracker(i)
        if tracker.get_type() == ARVRServer.TRACKER_CONTROLLER and tracker.get_tracker_id() == arvr_controller:
          var move_to_position = tracker.get_position()
          
          ## perform move_and_slide
          ...
          
          return
  
    ## couldn't find tracker...
    return
```

**Comment by Malcolmnixon** [comment]
I believe this is ready to be closed now.

**Comment by BastiaanOlij** [comment]
This should indeed be solved now. Closing this.
