### ISSUE TITLE
VR Template

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot-xr-tools#329]
Main branch (the demo) seams as good template for starting new game/app. I think there should be bit more variety(colours included) of grid textures(I am aware each person can generate their own if needed). Also white grid godot text should be darker or slightly different colour cause it is hard to read.

Also Settings should have place to choose preferred movement mode (teleport or smooth)

**Comment by BastiaanOlij** [comment]
The demo is definitely a good place to start, just gutting out everything but the main level. That said, we've recently moved a lot of the base logic into the plugin so recreating that wouldn't take a lot of time in a fresh project.

I'm not a fan of just adding textures to create a texture library, that would be better served by a separate asset (and indeed I think one of Kenneys assets in the asset library has this). We may even decide at some point to start adding much nicer objects and textures to the demo which aren't useful to someone starting a new project.

That said, if you believe the contrast on some of the images is bad, please feel free to submit a PR with better images. I generated these off of wahooney.itch.io so they're pretty much generated with default settings.

As for settings, in this case that is up to someone developing a game. For the demo we're purposefully showcasing each option, the purpose for the demo is to demonstrate how each feature works, so it doesn't make sense if the user chooses they want to use smooth movement, when you go into a demo that demonstrates how the teleport works.

But for a normal game, absolutely agree this is a sound design choice.

**Comment by pietru2004** [comment]
- About image thing, well thtat makes sense

- About the settings, well I guess ok, I have not yet looked deep into gui, but I guess it might be not a problem given that some demos require smoth movement.

**Comment by BastiaanOlij** [comment]
We now have a home for a template as described: github.com/GodotVR/godot-xr-template
