### ISSUE TITLE
Velocity in move_and_slide() should not be multiplied by delta

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#33]
The [docs for `move_and_slide()`](https://docs.godotengine.org/en/stable/classes/class_kinematicbody.html?highlight=move_and_slide#class-kinematicbody-method-move-and-slide) say:

>This method should be used in Node._physics_process (or in a method called by Node._physics_process), as it uses the physics step's delta value automatically in calculations. Otherwise, the simulation will run at an incorrect speed.

>linear_velocity is the velocity vector (typically meters per second). Unlike in move_and_collide, you should not multiply it by delta -- the physics engine handles applying the velocity.

Unfortunately we have on [line 161 of Function_Direct_movement.gd](https://github.com/GodotVR/godot-xr-tools/blob/2d680e504df87e7120d87ac1d04f90346ea605d3/addons/godot-xr-tools/functions/Function_Direct_movement.gd#L162)

```GDscript
velocity = controller.global_transform.basis.z.normalized() * -delta * max_speed * ARVRServer.world_scale
velocity = $KinematicBody.move_and_slide(velocity)
```

Same thing around [line 249](https://github.com/GodotVR/godot-xr-tools/blob/2d680e504df87e7120d87ac1d04f90346ea605d3/addons/godot-xr-tools/functions/Function_Direct_movement.gd#L249)

```GDscript
velocity = dir.normalized() * -forwards_backwards * delta * max_speed * ARVRServer.world_scale
...
# apply move and slide to our kinematic body
velocity = $KinematicBody.move_and_slide(velocity, Vector3(0.0, 1.0, 0.0))
```
I did wonder why I had to set the value to 250m/s to get anywhere!

I really don't like this design for the Godot function: delta should be passed in as a parameter to `move_and_slide()` instead of it ingesting it some other magical way.

I found this while trying to hack in some kind of climbing/crawling feature where you hook in a spike or a hook from your hand into the environment collision object to pull yourself along without using a trigger button (which is the convention for grab).  The challenge is working out how to dehook, which I am hoping to do by pulling while your KineticBody pushes you away.

**Comment by BastiaanOlij** [comment]
Good point, indeed delta somehow gets magically mixed in with move and slide, it's a little annoying :)
breaking change though but I'm not against it.

**Comment by BastiaanOlij** [comment]
Sorry for the long wait but applied this fix, thanks for suggesting it!
