### ISSUE TITLE
Godot 4 Beta 14 - XR Tools Demo - Latest Plugin

### ISSUE THREAD

**Issue by sprobst76** [GodotVR/godot-xr-tools#342]
Hello, 

I wanted to test Godot 4 with VR on the Quest 2. I tried to export the APK and got following issue, as soon i enable Godot Open XR Meta:

> Task :preBuild UP-TO-DATE
> Task :preDebugBuild UP-TO-DATE
> Task :mergeDebugNativeDebugMetadata NO-SOURCE
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript NO-SOURCE
> Task :generateDebugBuildConfig UP-TO-DATE
> Task :checkDebugAarMetadata UP-TO-DATE
> Task :generateDebugResValues UP-TO-DATE
> Task :generateDebugResources UP-TO-DATE
> Task :mergeDebugResources UP-TO-DATE
> Task :mapDebugSourceSetPaths
> Task :createDebugCompatibleScreenManifests UP-TO-DATE
> Task :extractDeepLinksDebug UP-TO-DATE

> Task :processDebugMainManifest FAILED
C:\Users\stefa\Downloads\godot-xr-tools-demo-4.0\godot-xr-tools\android\build\src\debug\AndroidManifest.xml:55:13-32 Error:
	Attribute meta-data#com.oculus.supportedDevices@value value=(all) from AndroidManifest.xml:55:13-32
	is also present at [godotopenxrmeta-debug.aar] AndroidManifest.xml:20:13-50 value=(quest|quest2|questpro).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:53:9-55:35 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugMainManifest'.
> Manifest merger failed : Attribute meta-data#com.oculus.supportedDevices@value value=(all) from AndroidManifest.xml:55:13-32
  	is also present at [godotopenxrmeta-debug.aar] AndroidManifest.xml:20:13-50 value=(quest|quest2|questpro).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:53:9-55:35 to override.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
8 actionable tasks: 2 executed, 6 up-to-date

Exit Code: 1

_Any Idea to fix that?_

**Comment by Malcolmnixon** [comment]
There's a bug for this in the godot_openxr_loaders. For now I would jump back to the previous build of the quest loader. 

https://github.com/GodotVR/godot_openxr_loaders/issues/19

**Comment by sprobst76** [comment]
Thank you for the quick reply! It solved my problem!

**Comment by BastiaanOlij** [comment]
Should all be resolved now with the latest RC and loaders plugin. There were a bunch of manifest changes we had to apply.
