### ISSUE TITLE
HTC Vive Focus 3 Support 

### ISSUE THREAD

**Issue by sprobst76** [GodotVR/godot-xr-tools#356]
Hello, 
I got in touch with Bastiaan via Youtube and wanted to test the plugin with the Vive Focus 3
![Screenshot_20230201_184912](https://user-images.githubusercontent.com/31782108/216123719-414fc52a-fd3f-448b-aa8e-6a9361e7a14a.png)
Unfortunately the Focus 3 sorts the app to 2D apps and returns an error as seen in the screenshot. I used Godot OpenXR Pico plugin as the Quest plugin does not work on my headset. 

Do you have any idea?

Best regards
         Stefan

**Comment by Psychophylaxis2** [comment]
https://github.com/GodotVR/godot_openxr_loaders/issues/25
It works correctly if you use the Khronos library that was just added to the loader and add the line in that link to the android manifest template file.

**Comment by BastiaanOlij** [comment]
Indeed, this should now work so if someone with an HTV Vive Focus 3 could test, that would be awesome

**Comment by sprobst76** [comment]
Unfortunately the quick "stupid" approach results in a black screen after the godot splashscreen. I have to look for it at the weekend!
![2023-02-24 14_02_24-Export](https://user-images.githubusercontent.com/31782108/221185495-3bfde8b6-1983-4927-a44d-769ec3970af2.png)

**Comment by sprobst76** [comment]
Attached you find the logcat log and the error output from Godot. There seems to be a problem with some texture. 
![2023-02-25 14_52_02-(_) main_menu_level tscn - Godot XR Tools Demo - Godot Engine](https://user-images.githubusercontent.com/31782108/221360646-1c2904bf-754f-48f9-8742-22d99f5871fc.png)
![2023-02-25 12_26_23-My Application – MainActivity kt  My_Application app main](https://user-images.githubusercontent.com/31782108/221360664-fe712cb3-5346-412a-8636-1d1757fd3368.png)

**Comment by Psychophylaxis2** [comment]
My settings that work on my Vive Focus 3 latest firmware, note I set the immersive mode which I didn't see in your screenshot.
You must also have the addition to the manifest file in the android/build/ folder. I made no other changes.

![image](https://user-images.githubusercontent.com/101484647/221442571-0c496915-c5fe-41c2-8b4b-d5bab89e94b9.png)

![image](https://user-images.githubusercontent.com/101484647/221442593-f9cb9157-c75d-4615-b744-bc561c8400a8.png)

![image](https://user-images.githubusercontent.com/101484647/221442708-dbae7838-19ed-40d0-891f-36de67df2232.png)

**Comment by Psychophylaxis2** [comment]
Also to note I used the bleeding edge godot-xr-tools-4.0-dev branch

**Comment by Psychophylaxis2** [comment]
It looks to me that the shared library isn't being located, did you follow all the setup instructions at https://github.com/GodotVR/godot_openxr_loaders

If you can upload a simple version somewhere I'm happy to give it a go with my setup.

**Comment by BastiaanOlij** [comment]
I'm closing this issue as it's not an issue with XR Tools. This probably should be raised either on Godot itself or on the loaders repo.

HTC Vive Focus 3 support in theory should work through the Khronos loader, but without access to hardware it's hard to test and figure out whats going wrong.
