### ISSUE TITLE
Player body default values should be adjusted to better match human 

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#360]
The default player configuration can make it difficult to pick up items. Specifically it has the following two default values of interest:
 - player_radius = 0.4 - can limit how close the player can get to a table or box
 - player_height_min = 1.0 - can limit how far a player can bend down to pick something off the ground

Rough statistics show:
 - Average human waste radius = ~0.2 m
 - Average human arm length = ~0.6 m

I cannot find good data on the eye position in relationship to the body center. Care would be needed to adjust the eye_forward_offset to prevent the near-clipping-plane of the camera allowing the player to see through walls.

**Comment by lunarcloud** [comment]
Yes, can concur. 
It wasn't obvious why the ground moved away when grabbing something from the ground lol

**Comment by Malcolmnixon** [comment]
Testing shows this works much better than the older settings.
