### ISSUE TITLE
Quest refresh rate

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot-xr-tools#363]
This is a problem that in part needs to be solved in the OpenXR plugin and we're investigating things further, but even with the base problem solved, there is still an improvement to do here in `start_xr.gd`.

The Quest 2 can run at multiple refresh rates. By default it reports it is set to 90hz giving us a framerate of 90fps.
The bug we've encountered is that it is lying, it is actually running at 72hz, probably because the manifest states that both Quest 1 and Quest 2 are supported, and Quest 1 runs at a maximum of 72.

We can request the available framerates by calling `OpenXRConfig::get_available_refresh_rates()` which returns an array of refresh rates. Note that for systems that do not support the refresh rate extension this array will be empty, and for systems where the refresh rate can't be changed, we just get the current set refresh rate.

> Framerate information is not available until after the OpenXR session is ready.

We need to add a mechanism that selects a suitable refresh rate and then calls `OpenXRConfig::set_refresh_rate()`.
The Quest 2 supports 60, 72, 90 and 120, it may not be advisable to always pick 120. We may wish to add a property of the maximum refresh rate we wish to choose.

The code will thus become something like:
```
# Handle OpenXR session ready
func _on_openxr_session_begun() -> void:
	print("OpenXR: Session begun")

	# Our interface will tell us whether we should keep our render buffer in linear color space
	get_viewport().keep_3d_linear = _openxr_configuration.keep_3d_linear()

	# get supported rates
	var available_rates = _openxr_configuration.get_available_refresh_rates()
	if available_rates.size() > 0:
		# todo, remove rates higher than maximum
		
		# select the highest rate
		_openxr_configuration.set_refresh_rate(available_rates[-1])

	# increase our physics engine update speed
	var refresh_rate : float = _openxr_configuration.get_refresh_rate()
	if refresh_rate > 0:
		# Report provided frame rare
		print("OpenXR: HMD refresh rate is set to ", str(refresh_rate))
	else:
		# None provided, assume a standard rate
		print("OpenXR: No refresh rate given by XR runtime")
		refresh_rate = 144
```

**Comment by DigitalN8m4r3** [comment]
just a day before i was eager to see how my overkill scenery would perform and i was surprised that it always showed 72 fps and then i compared it to the standard xr tools demo scenes and the same fps. So yeah this really needs to get sorted.
Good work on investigating the issue there.

for what its worth, a simple .gd script outputed the current fps
`extends Label3D

func _ready():
	set_process(true)
	
func _process(_delta: float):
	self.text = 'FPS: %s' % Engine.get_frames_per_second()
`
attached it to a Label3D Node and placed it under one of the Hands

**Comment by Malcolmnixon** [comment]
On my quest 2 (with 120Hz enabled in its settings) the _openxr_configuration.get_refresh_rate() always returns 90 even if I've called  _openxr_configuration.set_refresh_rate with 72 or 120. I'm just downloading the latest godot_openxr build from Nov 10 to confirm. Note that this is on Godot 3.5.1, not the Godot 4 betas.

**Comment by Malcolmnixon** [comment]
Under the assumption that changing the refresh rate may be delayed, I added a few more hooks to read the rate as the session changes. The following is the results:
```
OpenXR: Configuring interface
OpenXR: Initializing interface
Running on OpenXR runtime: Oculus 49.186.0
OpenXR Runtime only supports OpenGL version 3.0 - 3.2! Usually this is not a problem, continuing...
OpenXR Using OpenGL version: OpenGL ES 3.2 V@0667.0 (GIT@59a14ebd51, I5463b91de8, 1661831993) (Date:08/29/22)
OpenXR Using OpenGL renderer: Adreno (TM) 650
OpenXR: System name: Oculus Quest2
OpenXR: Session begun
OpenXR: Targetting refresh rate of 120
OpenXR: Target refresh rates are [60, 72, 80, 90, 120]
OpenXR: Setting refresh rate to 120
OpenXR: HMD refresh rate is set to 90
Setting physics rate to 90
_on_openxr_session_synchronized
   OpenXR: HMD refresh rate is set to 90
_on_openxr_visible_state
   OpenXR: HMD refresh rate is set to 90
_on_openxr_focused_state
   OpenXR: HMD refresh rate is set to 90
   OpenXR: XR started (focused_state)
```

Then with the game running I pressed the oculus menu button and got the following:
```
_on_openxr_visible_state
   OpenXR: HMD refresh rate is set to 120
   OpenXR: XR ended (visible_state)
_on_openxr_focused_state
   OpenXR: HMD refresh rate is set to 120
   OpenXR: XR started (focused_state)
_on_openxr_visible_state
   OpenXR: HMD refresh rate is set to 120
   OpenXR: XR ended (visible_state)
```

**Comment by Malcolmnixon** [comment]
I have a PR which should work. It reports the following for my quest:

target_refresh_rate = 0.0 (none):
```
	OpenXR: Configuring interface
	OpenXR: Initializing interface
	Running on OpenXR runtime: Oculus 49.186.0
	OpenXR Runtime only supports OpenGL version 3.0 - 3.2! Usually this is not a problem, continuing...
	OpenXR Using OpenGL version: OpenGL ES 3.2 V@0667.0 (GIT@59a14ebd51, I5463b91de8, 1661831993) (Date:08/29/22)
	OpenXR Using OpenGL renderer: Adreno (TM) 650
	OpenXR: System name: Oculus Quest2
	OpenXR: Session begun
	OpenXR: Refresh rate reported as 90
	OpenXR: Available refresh rates are [60, 72, 80, 90, 120]
	OpenXR: Setting refresh rate to 90
	Setting physics rate to 90
	OpenXR: XR started (focused_state)
```

target_refresh_rate = 72.0:
```
	OpenXR: Configuring interface
	OpenXR: Initializing interface
	Running on OpenXR runtime: Oculus 49.186.0
	OpenXR Runtime only supports OpenGL version 3.0 - 3.2! Usually this is not a problem, continuing...
	OpenXR Using OpenGL version: OpenGL ES 3.2 V@0667.0 (GIT@59a14ebd51, I5463b91de8, 1661831993) (Date:08/29/22)
	OpenXR Using OpenGL renderer: Adreno (TM) 650
	OpenXR: System name: Oculus Quest2
	OpenXR: Session begun
	OpenXR: Refresh rate reported as 90
	OpenXR: Available refresh rates are [60, 72, 80, 90, 120]
	OpenXR: Setting refresh rate to 90
	Setting physics rate to 90
	OpenXR: XR started (focused_state)
```

target_refresh_rate = 144.0:
```
	OpenXR: Configuring interface
	OpenXR: Initializing interface
	Running on OpenXR runtime: Oculus 49.186.0
	OpenXR Runtime only supports OpenGL version 3.0 - 3.2! Usually this is not a problem, continuing...
	OpenXR Using OpenGL version: OpenGL ES 3.2 V@0667.0 (GIT@59a14ebd51, I5463b91de8, 1661831993) (Date:08/29/22)
	OpenXR Using OpenGL renderer: Adreno (TM) 650
	OpenXR: System name: Oculus Quest2
	OpenXR: Session begun
	OpenXR: Refresh rate reported as 90
	OpenXR: Available refresh rates are [60, 72, 80, 90, 120]
	OpenXR: Setting refresh rate to 120
	Setting physics rate to 120
	OpenXR: XR started (focused_state)
```
