### ISSUE TITLE
orthonormalized() should be applied to transform after rotation

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#37]
There two lines in the code https://github.com/GodotVR/godot-xr-tools/blob/master/addons/godot-xr-tools/functions/Function_Direct_movement.gd#L216  https://github.com/GodotVR/godot-xr-tools/blob/master/addons/godot-xr-tools/functions/Function_Direct_movement.gd#L180 which say:

```GDscript
origin_node.transform *= t2 * rot * t1
```

To avoid losing tolerance they should probably read:
```GDscript
origin_node.transform = (origin_node.transform * t2 * rot * t1).orthonormalized()
```

I had a nasty run-in with this issue at https://github.com/godotengine/godot/issues/43320

**Comment by BastiaanOlij** [comment]
Sorry for the long wait but applied this fix, thanks for suggesting it!
