### ISSUE TITLE
The player height cannot be adjusted correctly

### ISSUE THREAD

**Issue by Eisenspalter** [GodotVR/godot-xr-tools#375]
The player height cannot be adjusted correctly. Very often, I can't adjust the player height setting because I can't reach the menu. Would make more sense to use laser pointers. These are more flexible

**Comment by BastiaanOlij** [comment]
One option Malcolm and myself discussed the other day was to use the initial main scene load as a calibration. Seeing we have the "press trigger to continue" in the loading screen we can be pretty sure the player is standing up properly (or sitting down if you are playing seated) when the main scene loads. We can capture the height of the player at that moment.

**Comment by Eisenspalter** [comment]
I totally agree. Main scene load as a calibration is the best approach. A lot of games do this. E.g. Population: One. Population: one also has one of the the best climbing experience.

**Comment by Malcolmnixon** [comment]
Pull Request #475 adds support for automatic player height calibration.

**Comment by BastiaanOlij** [comment]
This has been improved in #475 as Malcolm states, closing this issue.
