### ISSUE TITLE
FogVolume problems

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot-xr-tools#381]
![20230222010310_1_vr](https://user-images.githubusercontent.com/51274570/220487278-2e1b53ab-820c-40a9-b521-814c8af4292d.jpg)
each eye has diffrent fog level

**Comment by Malcolmnixon** [comment]
This is definitely more of a Godot rendering issue and should be submitted on the normal Godotengine repository, however it would be valuable to note whether this occurs on Godot 3 or Godot 4 and which renderer is being used gles2, gles3, vulkan mobile, or vulkan forward+

**Comment by pietru2004** [comment]
I tested it on gd4 rc2 forward+

śr., 22 lut 2023, 05:16 użytkownik Malcolm Nixon ***@***.***>
napisał:

**Comment by BastiaanOlij** [comment]
I don't think fog volumes have been updated for stereoscopic rendering yet.  But indeed as Malcolm states, please raise this as an issue on the Godot repository, this is unrelated to XR Tools.

**Comment by pietru2004** [comment]
Ok I will

**Comment by Calinou** [comment]
This is indeed an [engine issue](https://github.com/godotengine/godot/issues/72331), so this one should be closed.
