### ISSUE TITLE
XRToolsInteractableAreaButton emiting signal

### ISSUE THREAD

**Issue by nox123** [GodotVR/godot-xr-tools#383]
i think i found issue with XRToolsInteractableAreaButton
it is emit_signal("button_released")
but should be emit_signal("button_released",_button)

**Comment by Malcolmnixon** [comment]
Good catch. I originally checked the master branch and couldn't find the problem - it's only the 4.0-dev branch that's broken.

**Comment by Malcolmnixon** [comment]
Tested and working
