### ISSUE TITLE
4.0 -dev climb bug

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot-xr-tools#389]
when I try to catch with climb in grapling demo I get this
![obraz](https://user-images.githubusercontent.com/51274570/221180747-4f930bde-f8d2-4ecd-8683-a74340cc2bfc.png)

**Comment by Malcolmnixon** [comment]
Good catch. I thought I had replaced all of these. Could you try out the change in the draft pull request and let me know if it fixes your issue.

**Comment by pietru2004** [comment]
gona check when I find a minute

**Comment by pietru2004** [comment]
Seams to work
