### ISSUE TITLE
XRTools Drab Point Hand problem

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot-xr-tools#391]
![obraz](https://user-images.githubusercontent.com/51274570/221370542-090a62c0-7b35-40ec-b1e6-d02de062614e.png)
hands started duplicating themselfs
![obraz](https://user-images.githubusercontent.com/51274570/221370552-ad5c5c3f-bea4-48ca-8ff8-b29f53312589.png)
plus there is null variable name

**Comment by pietru2004** [comment]
Also it does not seam to be duplicated uids as in https://github.com/GodotVR/godot-xr-tools/issues/352

**Comment by Malcolmnixon** [comment]
This seems to be a new issue with Godot 4.0 RC5 only - it doesn't occur with RC4 or earlier.

**Comment by Malcolmnixon** [comment]
This was a problem introduced with https://github.com/godotengine/godot/pull/73870 and released with Godot 4.0 RC5, and subsequently reverted in https://github.com/godotengine/godot/pull/73933.

For now you could either use RC4, wait for RC6, or build a version from master.
