### ISSUE TITLE
Snap zone should support scripted request to snap an item

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#400]
The XRToolsSnapZone script has a function to safely request it pick up an object; however that function is called `_pick_up_object` which is private and gdlint complains of any attempt to call it. The function should be renamed to `pick_up_object` so it can be called externally.

**Comment by DigitalN8m4r3** [comment]
indeed, in my case regarding the basic inventory, this ends up with exactly 2 errors related to this issue and from talkin to malcolm, there is no way around the _pick_up_object, it needs to be made public so that future work such as the backpack inventory and some other things can be done properly

**Comment by Malcolmnixon** [comment]
This works as intended and has been added to the pickable demo scene.
