### ISSUE TITLE
4.0.stable  playerbody falls through floor

### ISSUE THREAD

**Issue by flobotics** [GodotVR/godot-xr-tools#413]
hi,
i installed godot 4.0-stable and godot-xr-tools newest release for 4.0 . Then i created a very simple VR game for windows, but after adding MovementDirect to the RightHand controller node and press play, the player falls through the floor (floor got rigid-body with collision-shape) ?

I noticed there is the player body node automatically added.

what do i need todo, to collide with floor ?

thanks
flo

**Comment by Malcolmnixon** [comment]
I just tried it and I'm not having this problem. You may want to make sure the Godot XR Tools plugin is enabled in the Plugins tab of the project settings. Additionally you may wish to make sure the ground collider is on layer 1.

**Comment by flobotics** [comment]
the plugin is enabled. With "ground collider" do you mean the "Collision->Layer" of the RigidBody of the Floor node ?  If so, with this set to 1 and the PlayerBody->Collision->Layer also set to 1 (was only on 20) .

But i fall through the floor.

In PlayerBody there is also a Moving_Platform->Floor_Layers where all layers are enabled by default.

**Comment by Malcolmnixon** [comment]
I put together this quick demo - the following is the player body:
![image](https://user-images.githubusercontent.com/1863707/222932447-a6d21fcc-793c-4df7-82ae-3a824d12e5be.png)

And this is the static ground node:
![image](https://user-images.githubusercontent.com/1863707/222932509-e5332b03-5fc0-45b7-9f82-62dfea3799b5.png)

The important parts are:
 - The PlayerBody - Collision - Mask has bits set which indicate the body will collide with objects on layer 1
 - The Ground - Collision - Layer has bit 1 set indicaing the ground is on layer 1

**Comment by flobotics** [comment]
i stand on the floor when i have NOT added to the righthand the movementDirect scene .  When i add this scene to my righthand controller, i fall through the floor

**Comment by Malcolmnixon** [comment]
Yes - I have movementDirect nodes added to both controllers, and I'm able to move and strafe around the scene. Would it be possible to zip up the project (excluding the .godot folder) and attach to this issue.

**Comment by flobotics** [comment]
[project.zip](https://github.com/GodotVR/godot-xr-tools/files/10890445/project.zip)

here, if it works

**Comment by Malcolmnixon** [comment]
I found two issues:
 1. Your ground collider is a "RigidBody3D" - a dynamic body affected by gravity, and so the ground collider actually falls away under the player. Note the mesh isn't a child of the RigidBody so its image stays behind like the Cheshire cat's grin ;)
 2. The player origin (the floor level of the tracking space) starts at position 0,0,0 (center of the universe), but the ground is a rectangle 1 meter thick, whose body is centered also at 0,0,0 - in other words your feet start life embedded 1/2 a meter into the ground; and that's probably going to cause issues with the physics engine.

You can fix these by changing the ground to be a StaticBody and then moving it down to Y=-0.5 so the top of the ground is at 0,0,0.

**Comment by flobotics** [comment]
thanks, i am very thankful for your help.   StaticBody3d  was the killer

thx alot @Malcolmnixon
