### ISSUE TITLE
Missing error handling when scene loading fails

### ISSUE THREAD

**Issue by ChristophHaag** [GodotVR/godot-xr-tools#416]
https://github.com/GodotVR/godot-xr-tools/blob/aaf97e09fab8fdfd9439569596b12af5f29b9147/addons/godot-xr-tools/staging/staging.gd#L195

load_threaded_get_status can return THREAD_LOAD_FAILED which gets ignored. `new_scene` is null and you get an exception at

https://github.com/GodotVR/godot-xr-tools/blob/aaf97e09fab8fdfd9439569596b12af5f29b9147/addons/godot-xr-tools/staging/staging.gd#L226

**Comment by Malcolmnixon** [comment]
I'm not sure what the response should be in this case. We could do:
```gdscript
assert(new_scene != null, "Error loading %s." % p_scene_path)
```

Other options might be to add a `scene_load_error` signal, but it's unclear what the code would do after calling the error - should it just return assuming the handler will "do the right thing"?

**Comment by BastiaanOlij** [comment]
Talking this over with Malcolm, all we can do is make sure the loading issue is reported, there is no good way to recover from this.
