### ISSUE TITLE
Mac support for Godot XR

### ISSUE THREAD

**Issue by eelcor** [GodotVR/godot-xr-tools#418]
Hi,

I am very enthusiastic about Godot and want to switch from Unity. I am a hobbyist using an M1 Max MacBook Pro and love to program and create content. Unfortunately there is one thing holding me back from completely switching. I haven't found a way to use VR with Godot (Mac support for VR is overall sketchy, but within Unity I can develop for my Quest 2 headset).

Is there any way to get support for using the Quest 2 with Godot 4.0 on a Mac? I'd be more than happy to help, but my coding skills are limited. I have no issues with getting my hands dirty and try things ;) How can I cross compile the tools for Mac OS? Are there any plans to support Macs in the future as the M1/M2..MX processors seem to be more suitable for 3D graphics.

Kind regards,
Eelco

**Comment by BastiaanOlij** [comment]
Hi Eelco,

There is no fundamental difference here between Unity and Godot. It is just a matter of installing Android Studio on the Mac so ADB is installed and you can push APKs to your Quest.

For Godot itself just download the universal Mac build and you can run the editor, then download the loader library and XR Tools from the asset library.

The only limit on Mac is that here are no headsets to my knowledge that allow for running the VR project locally with something like airlink. You have to push your project to the Quest.

**Comment by eelcor** [comment]
Thank you so much!!!

I hope air link support will be added soon for the Meta Quest, as 3D capabilities of the new Mac's have been greatly improving. But now I am so happy with your answer!

**Comment by BastiaanOlij** [comment]
Happy new, OpenXR added support for macOS so we enabled it!!

https://github.com/godotengine/godot/pull/79614
Coming in 4.2

**Comment by eelcor** [comment]
Dear Bastiaan,

Thank you so much for your effort! I am really happy!

Kind regards,
Eelco

Op za 29 jul. 2023 om 06:04 schreef Bastiaan Olij ***@***.***>

**Comment by BastiaanOlij** [comment]
Glad you can move forward @eelcor  :)

Closing this issue.
