### ISSUE TITLE
Current master doesn't run on Ouest2

### ISSUE THREAD

**Issue by Eisenspalter** [GodotVR/godot-xr-tools#429]
I installed the master version to see what's new. PCVR is running, Ouest2 doesn't. After pressing the trigger in the splash screen I see only a black screen

**Comment by Malcolmnixon** [comment]
Please re-test with [4.0.2 RC 1](https://godotengine.org/article/release-candidate-godot-4-0-2-rc-1/) as this is the first version that includes the ([GH-74684](https://github.com/godotengine/godot/pull/74684)) fix for an issue which causes that scene-loading failure and black screen.

**Comment by Eisenspalter** [comment]
Everything works great now!

**Comment by valoalbert** [comment]
I have the 4.0.2 stable and it's not launching. It remains with the Quest's black loading screen until it closes eventually

**Comment by bferguson3** [comment]
Seconded, does not boot on Quest 2.

Using Godot 4.0.2 and xr tools demo 4.0.0.

Its difficult to parse the log, but the only crash trace with anything of use says: 

they all say `DEBUG   : Cause: null pointer dereference` but they trace back through Godot to ArtLib and then to libc, which is... real bad.

Note that the program launches fine in the editor, it is only when building to quest it fails to run.

**Comment by Malcolmnixon** [comment]
Is it possible for you to capture a log using adb and attach it to this issue.

**Comment by da-molchanov** [comment]
Exporting the current master (Godot XR Tools 4.1.0) from Godot 4.0.2-stable works on my Quest 2. I used the following steps to export the project for the first time:
1. Clone and import the project
2. Project->Install Android Build Template...
3. Download and install "Godot XR Android OpenXR Loaders" from the AssetLib
4. Project->Export->Android Quest (Runnable)
5. Check Plugins->Godot Open Xr Meta and make sure it is the only one checked
6. Export Project...
7. Install the .apk and run the demo

The demo loads fine and all levels work as expected (although I am getting ~45 fps most of the time, and ~10 fps when standing on the mounds in the basic movement, teleport and sphere world scenes)

**Comment by BastiaanOlij** [comment]
Closing this as indeed this should work fine now. There were issues in the early 4.0 builds. Godot 4.0.3 has been very stable, so has Godot 4.1.
