### ISSUE TITLE
Add rotation to when releasing objects

### ISSUE THREAD

**Issue by Noobidoo** [GodotVR/godot-xr-tools#43]
For throwing things having the object rotate based on controllers rotation would make it more immersive.
Tried to work out the math for it my self but only found a non optimal way to do it.

**Comment by BastiaanOlij** [comment]
Will work on that soon, its something I've wanted to add for awhile.

**Comment by BastiaanOlij** [comment]
I've got it working in my WIP Godot 4 port, I'll find some time to add a PR for the current version tomorrow. It's incredibly satisfying throwing something into the air and make it spin :)

**Comment by Noobidoo** [comment]
Nice. Looking forward to learn how you solved it.
