### ISSUE TITLE
Climbing in Sprinting demo does not work

### ISSUE THREAD

**Issue by toedter** [GodotVR/godot-xr-tools#431]
While climbing works perfectly (using HP Reverb G2) in the Gliding and Climbing demo, it does not work in the Sprinting demo.
The instructions tell that climbing should be enabled with "grab".

**Comment by Malcolmnixon** [comment]
Good catch - this was broken by some layers cleanups. I have a fix pending in some PRs that will hopefully go through in the next few days.

**Comment by Malcolmnixon** [comment]
This was fixed by https://github.com/GodotVR/godot-xr-tools/pull/432 and is now working in the master branch.
