### ISSUE TITLE
@tool annotation added to interactable scripts breaks snap zone if initial object is used

### ISSUE THREAD

**Issue by LaserPanzerWal** [GodotVR/godot-xr-tools#434]
Recently, the tool annotation was added to several scripts, including interactables.
This results in issues if an initial object is added to a snap zone, as the picking up functions are now called in the editor changing both physics layers and freeze state. As a result, when picking up said item in game, once let go it will get stuck at the last held position (due to still being frozen) and cannot be picked up again because the physics layer will stay on 17.
There may be more issues caused by the change, as other scripts may also change variables while in editor.

This is especially annoying if the issue is noticed at a later point, as all affected scenes loaded into the editor until then will have to be either changed back manually or retrieved from git and then merged to apply the intended changes.

**Comment by Malcolmnixon** [comment]
Could you check out the branch and see if it fixes your issue.

**Comment by LaserPanzerWal** [comment]
It seems to have fixed the issue, thank you.
So far this was the only issue I noticed related to the aforementioned change, you may want to confirm the other files changed in that commit don't have similar effects though.
