### ISSUE TITLE
Viewport2Din3D input doesn't work correctly with multiline TextEdit

### ISSUE THREAD

**Issue by anunknowperson** [GodotVR/godot-xr-tools#447]
Viewport2Din3D raycasted input doesn't work correctly with multiline TextEdit.

cursor doesn't move at all

**Comment by Malcolmnixon** [comment]
I tracked this down in the godot text edit control and found that `TextEdit::is_mouse_over_selection()` uses `get_local_mouse_pos()` which uses `Viewport::get_mouse_position()`. This bypasses the virtual input system used by the Viewport2Din3D and tries going directly to the DisplayServer or Input singletons and getting the mouse position.

This will take a bit of effort to resolve.

**Comment by BastiaanOlij** [comment]
That as probably an issue that should be reported upstream. There are situations outside of XR where viewports are rendering 2D UIs where there is no direct translation between the mouse position on screen and the location within the viewport

**Comment by Malcolmnixon** [comment]
Could you try this out again with Godot 4.1.1 - I believe they reworked the control system to use the positions fed in rather than grabbing the physical mouse.

**Comment by BastiaanOlij** [comment]
Closing this as no recent updates, as far as we know this is working properly in the latest Godot release. There may have been an issue in older Godot versions but this is an upstream issue unrelated to XR Tools.

Please feel free to re-open this issue or create a new issue with more detail if problems persist.
