### ISSUE TITLE
Question about mobile

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot-xr-tools#451]
does exporting to portable headsets require mobile renderer or can it be forward+ ?

**Comment by Malcolmnixon** [comment]
I believe it can be forward+ but with a significant performance penalty. Mobile headsets have unique graphics pipeline limitations that don't exist on PC hardware.

**Comment by pietru2004** [comment]
Ok thank you for info, I have WMR so I couldn't check that myself.

**Comment by pietru2004** [comment]
I want to ask can I still use forward Plus if I have renderer settings like this?
![obraz](https://user-images.githubusercontent.com/51274570/232099060-1b3d11d3-69fe-47c9-9b65-c308e2ac0058.png)
I mean will it use RemderingMethod.mobile on XR standalone
