### ISSUE TITLE
On PICO hands showing problems without a Viewport2Din3D

### ISSUE THREAD

**Issue by robherre** [GodotVR/godot-xr-tools#457]
I don't know why, but if I don't instantiate a viewport_2d_in_3d.tscn I have one, depending of the rest of the scene, of the next problems with hands:

- Not showing at all
- Instead of hands it shows VERY BIG perpendicular planes that difficult watching the scene.
- I can see then hands but doesn't move the fingers when pulling the triggers.

If I add the mentioned scene to the scene -it can be disabled- it works correctly.

**Comment by Malcolmnixon** [comment]
I've been trying to track this one down for a while. Hands are animated by a vertex shader that takes a "texture" containing the bone transforms. Last night I found out that on Android (and probably all gles systems) this skeleton-texture update rate is somehow being coupled to the updates of viewports in the viewport_2d_in_3d.tscn. If the viewport is rate-limited to 1Hz then the hand bone angles update once a second.

**Comment by Malcolmnixon** [comment]
I tracked it down finally - https://github.com/godotengine/godot/pull/79772 - hopefully this makes it into an RC shortly.

**Comment by BastiaanOlij** [comment]
Closing this as the fix has been merged. It will be in the 4.2 release of Godot and may end up being cherry picked for 4.1.2
