### ISSUE TITLE
Add virtual keyboard

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot-xr-tools#46]
Something that came up on the Godot XR discord channel, having a virtual keyboard implementation people can just use would be really handy

**Comment by BenMcLean** [comment]
My idea  Thanks for working on or at least considering this. :)

**Comment by BastiaanOlij** [comment]
I'll find time for it some day soon

**Comment by Malcolmnixon** [comment]
I started looking into this, and playing with creating a simple 2D keyboard hosted in a Viewport_2D_in_3D that fires InputEventKey events. There are unfortunately a few issues with this:

### Internationalization
There are numerous keyboard layouts differentiated by region - https://en.wikipedia.org/wiki/Keyboard_layout#Physical,_visual,_and_functional_layouts.

To do a proper job would require using OS.get_locale() and then have a large number of keyboard definitions. This would probably be best handled by a JSON file containing all the supported locales, and dynamically creating the appropriate keyboard at runtime.

It's actually even more interesting than this - Chinese has a set of input methods which I believe take three keys in a row to make a single Chinese character.

A cheap hack with a few locales probably wouldn't be too difficult, but a proper general purpose implementation probably warrants its own Godot project, and the result of that project could possibly just be hosted in a Viewport_2D_in_3D.

### Hooking Godots Virtual Keyboard
Currently the LineEdit and TextEdit controls are hard-coded to call the OS.show_virtual_keyboard and OS.hide_virtual_keyboard functions. There's currently no way of "hooking" these functions and providing a custom virtual keyboard.

Without this "hooking" capability, dialogs and text controls would need custom code to manually request the VR keyboard show and hide itself on focus changes.

### Keyboard Types
It could be possible to just put up a full keyboard, but it would be better to optimize the type - text, number, phone, email, etc.

Godots virtual keyboard methods have no means of specifying or requesting the type of keyboard to show, although there is an open ticket for adding this feature - https://github.com/godotengine/godot-proposals/issues/1511

**Comment by Malcolmnixon** [comment]
I have a pull request which contains a virtual keyboard. You can place it anywhere in the scene, including attached to the player, although that didn't seem to work well for me.

![image](https://user-images.githubusercontent.com/1863707/152490517-fe2a10b6-a235-485a-bbec-09210a2190e3.png)

**Comment by goatchurchprime** [comment]
Some quibbles having tried it out.
* characters are emitted at the wrong time. This is because you're using pressed signal (which is actually on button up) instead of button_down. 
* repeat key feature (probably would get this using button_down instead of pressed.  keyboard keys work very slightly different from button UI.
* needs punctuations keys:;,.()
* also nice to have cursor key arrows as easier than scroll bars.  and a clear textarea, and undo.
* sounds or controller vibrations when moving across or pressing are necessary.
