### ISSUE TITLE
Teleport Target Areas is an existing functionality?

### ISSUE THREAD

**Issue by elisagalofaro** [GodotVR/godot-xr-tools#472]
Is there a way to add "Teleport Target Areas" to make location areas in the scene where the user can teleport to them (like this: https://www.youtube.com/watch?v=Se92IOCl1Fo)?

**Comment by Malcolmnixon** [comment]
Pull request #508 adds teleport areas.

**Comment by elisagalofaro** [comment]
Thanks @Malcolmnixon!
