### ISSUE TITLE
playerbody's stop_on_slope seems not to  work properly

### ISSUE THREAD

**Issue by surreal6** [GodotVR/godot-xr-tools#477]
# The characterBody option stop_on_slope seems to fail.

There is no difference if you set this option to true or false, when you move (with movement direct) to a slope, the playerbody is pushed up to the slope. The more sloped, the fastest you move.

## How to reproduce the bug:

Run the example, move to the first slope (yellow one is 5 degrees) and stop moving, you will be moving up no matter if you set stop_on_slope on or off.  

The only way ti found to fix it is to add a custom physics behaviour and uncheck the stop_on_slope in the custom XRToolsGroundPysics

Maybe i am not understanding how to use the option, but it seems to me thats not the intended behaviour

## demo project 

I put together a sample project where you can replicate the bug:

(note that you will need to install xr tools from the asset manager in the demo project)

[https://github.com/surreal6/player_slide_on_slope_bug](https://github.com/surreal6/player_slide_on_slope_bug)

![Captura3](https://github.com/GodotVR/godot-xr-tools/assets/437199/7d7eb569-8a96-4005-80ca-6f0e83379f16)

**Comment by Malcolmnixon** [comment]
This should be fixed now in the main branch. Could you try it out and confirm.

**Comment by BastiaanOlij** [comment]
Closing this as fixed. If there are further issues please open up a new issue with a demo project showing the issue.
