### ISSUE TITLE
MacOS doesn't support OpenXR Action maps

### ISSUE THREAD

**Issue by eelcor** [GodotVR/godot-xr-tools#479]
Dear Developers,

I'm probably asking this question in the wrong issue tracker, because of the changes with Godot 4. I wanted to have more direct access to the touch controllers to steer a spaceship. However when I read the documentation regarding the OpenXR Action map, I cannot get it to work for the Mac. I tried with Catalina (old intel MacBook) and Ventura (my current M1 Max MacBook) If I try to add the "openxr_action_map.tres" resource to my project, I get multiple errors stating that the class does not exist. I also do not see the OpenXR Action map editor in the interface.

I have a feeling that it looks for the correct OpenXR API hooks and when it does not find it, it doesn't enable the classes. This is quite unfortunate as I develop for the Oculus Quest 2 and do a wired deployment to test my project.

I hope you can help me. I am willing to delve into the code and find the problem myself. Maybe Bastiaan has a starting point for me.

Kind Regards,
Eelco

**Comment by BastiaanOlij** [comment]
Indeed, wrong place to ask Eelco however good news, this has been resolved upstream in Godot. You can either use a nightly build or wait until 4.2 is officially released but it will have full support on macOS.

As a workaround for now you can grab the `openxr_action_map.tres` from the demo in this repo, you just can't customise it.

**Comment by Valkar13** [comment]
Workaround some times work but sometimes dont. One day controllets just stop working after i add openxr_action_map.tres to project on compilation for Oculus Quest 2 get errors"

  Cannot get class 'OpenXRActionSet'.
  Cannot get class 'OpenXRIPBinding'.
  Cannot get class 'OpenXRInteractionProfile'.
