### ISSUE TITLE
Snap turning not working with HP Reverb G2

### ISSUE THREAD

**Issue by toedter** [GodotVR/godot-xr-tools#485]
When checking out the latest main, I noticed that snap turning is not working anymore (using HP Reverb G2).
While the turning itself works, every time I turn I also move (probably strafe).

Tested it with both Godot 4.1.1 and 4.0.3.

**Comment by Malcolmnixon** [comment]
I believe this will be fixed by https://github.com/GodotVR/godot-xr-tools/pull/482

**Comment by Malcolmnixon** [comment]
This should be fixed now, could you check out the main branch and try again.

**Comment by toedter** [comment]
Thx a lot, it is fixed.
