### ISSUE TITLE
Feature request: More visual customizability

### ISSUE THREAD

**Issue by tcrass** [GodotVR/godot-xr-tools#500]
It's really cool to get so much XR functionality out of the box, but it would be even greater if it was possible to adjust the looks of many visual feedbacks to the style of the application they're used in. For instance, the teleport function provides some proerties allowing to change the color the beam should have depending on the beam's collision state (which is nice), but how about providing access to the beam's material so that it can be completely re-styled? Same holds true for the teleport target marker.
Furthermore, one might want to change the teleporter's player body capsule's color, material, or maybe even its shape. (Or hide it alltogether.)
Another example is the pointer function, which currently doesn't provide any visual customizations, be it the laser's color or the target marker's appearance.
I'm aware that this is a rather vague request, but I believe it would on the long run be worth spending some thoughts on this...

**Comment by Malcolmnixon** [comment]
Pull request #502 adds some of the functionality you're after for the pointer function.

**Comment by Malcolmnixon** [comment]
The teleport beam is implemented by a custom vertex/fragment shader to provide the arc and the animation, so the user would not be able to provide their own shader. It would however be possible to allow the user to provide their own arrow texture. I'll look into enhancing the options tomorrow.

**Comment by tcrass** [comment]
> Pull request #502 adds some of the functionality you're after for the pointer function.

Awesome, thanks!

**Comment by tcrass** [comment]
> The teleport beam is implemented by a custom vertex/fragment shader to provide the arc and the animation, so the user would not be able to provide their own shader. It would however be possible to allow the user to provide their own arrow texture. I'll look into enhancing the options tomorrow.

Personally, I like the arrow texture and animation. But I'd be really happy if it was possible to alter the visuals of the player teleportation target.

**Comment by Malcolmnixon** [comment]
Pull request #504 enhances the teleport to give you control over the arrow and target textures; and you can now set your own capsule material - including totally invisible to hide the capsule if desired.

**Comment by tcrass** [comment]
> Pull request https://github.com/GodotVR/godot-xr-tools/pull/504 enhances the teleport to give you control over the arrow and target textures; and you can now set your own capsule material - including totally invisible to hide the capsule if desired.

Ah, that's nice! Would it also be possible to allow for a custom mesh for the player's Capsule node?

**Comment by Malcolmnixon** [comment]
I added that option to #504

**Comment by Malcolmnixon** [comment]
I think this issue is probably good to close now that the visual customization features mentioned have been merged.

**Comment by BastiaanOlij** [comment]
Closing this as implemented. If there are additional things we should improve, please raise separate issues for these so we can track them.
