### ISSUE TITLE
Invalid get index 'playing' (on base: 'null instance') at addons/godot-xr-tools/objects/snap_zone.gd:248

### ISSUE THREAD

**Issue by jkankiewicz** [GodotVR/godot-xr-tools#505]
My Godot-4.1.1 project doesn't play a sound when snapping an `XRToolsPickable` into an `XRToolsSnapZone` and it crashes within `pick_up_object()` because an `AudioStreamPlayer3D` node is expected to exist.

**Comment by Malcolmnixon** [comment]
Could you test with the latest master branch, and if it's fixed we can close the issue.

**Comment by BastiaanOlij** [comment]
Closing this as fixed.
