### ISSUE TITLE
Add a vignette to help reduce motion sickness?

### ISSUE THREAD

**Issue by tony709394** [GodotVR/godot-xr-tools#52]
This feature should be common. But It doesn't seem to be possible to render directly to viewport via ColorRect. (For example, [official demo](https://docs.godotengine.org/en/stable/tutorials/vr/vr_starter_tutorial/vr_starter_tutorial_part_one.html#reducing-motion-sickness))

Devices: Oculus Quest 2 (No errors are printed)

**Comment by BenMcLean** [comment]
Personally, in C#, I use a camera with a "Veil" object to fade the screen as needed.
https://github.com/BenMcLean/WOLF3D-Godot/blob/master/godot/WOLF3DGame/FadeCamera.cs

**Comment by BastiaanOlij** [comment]
Rendering of 2D objects is disabled in XR interfaces using the GLES2 driver. Ben's solution is a good one.

And yes, fully agree we should have a solution as part of our xr-tools library

**Comment by BastiaanOlij** [comment]
This is a solution that works in 3D: https://github.com/GodotVR/godot-xr-tools/pull/53

**Comment by BastiaanOlij** [comment]
This is now solved through https://github.com/GodotVR/godot-xr-tools/pull/53
