### ISSUE TITLE
Get XRController3D name (HTC Vive, Index, Pico,...)

### ISSUE THREAD

**Issue by elisagalofaro** [GodotVR/godot-xr-tools#544]
Is it possible to obtain the name of the XRController3D used? 
I can see in the "OpenXR Action Map" tab all the labels for the supported controller, but I can't get the name of the controller in use. 
Moreover, I am able to detect the XRRuntime (SteamVR), so, somewhere I should read even the name of the controller, but I had no chance until now.... thanks!

**Comment by BastiaanOlij** [comment]
I don't think it's currently exposed, but probably worth exposing at some point. This will need to be done in Godot itself however.

**Comment by elisagalofaro** [comment]
Hello there! I just wanted to mention that this demo really solved my problem! 
https://github.com/godotengine/godot-demo-projects/pull/973 

Thank you! @BastiaanOlij
