### ISSUE TITLE
Function_pointer action error spam

### ISSUE THREAD

**Issue by dominiks** [GodotVR/godot-xr-tools#55]
Hi, when setting the `Function_Pointer`'s `Active Button` to `Vr Action` and set the name of one of my actions (100% defined in the project's Input map) the editor is filled with the error message

    The InputMap action "vr_right_trigger" doesn't exist. Did you mean "ui_right"?

The message disappears when I remove the `tool` declaration from the script (obviously). But I am not sure if it needs to be a `tool`.

**Comment by BastiaanOlij** [comment]
dangit, it needs to be a tool script for some of the options to work, which is annoying, but it needs extra checks to skip over the process code when running in the editor.

**Comment by BastiaanOlij** [comment]
Closing this as it is no longer an issue in the latest version. Note that in Godot 4 we've switched over to using the action map.
