### ISSUE TITLE
Remove acceleration in player movement to avoid motion sickness

### ISSUE THREAD

**Issue by fangzhangmnm** [GodotVR/godot-xr-tools#553]
Joystick input should change ground control velocity directly, instead of accelerating it. That's what most VR games do. Having acceleration in the virtual world is very likely to induce motion sickness and should be avoided.

Edit: Okay I can just change the drag and traction in the ground physics settings

**Comment by Malcolmnixon** [comment]
Yup - set those high and you'll get no acceleration. Set them low and you can emulate an icy/slippery floor.
