### ISSUE TITLE
Out of range grip values cause hands to remain partially gripped

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#57]
The Godot OpenXR library has an issue where the controller.get_joystick_axis(JOY_VR_ANALOG_GRIP) can report values outside of the 0.0 - 1.0 range (observed on Oculus Quest controllers).

This causes a secondary failure in the Godot XR Tools LeftHand.gd and RightHand.gd scripts which aren't robust to out-of-range values. These scripts just multiply the joystick position by 2.5 to produce animation tree positions. The result is that the animation tree positions can be outside of the legal range and the animation doesn't update. As such quickly releasing the grip button can result in the hand remaining partially gripped.

The solution appears to be adding the following line to LeftHand.gd and RightHand.gd after reading the controllers:
```
    grip = clamp(grip, 0.0, 2.5)
```

It may also be advisable to do the same protection on the trigger axis, just be robust to out-of-range values in the future.

**Comment by BastiaanOlij** [comment]
I need to find time to investigate this further, I think this should be a fix in the OpenXR plugin itself

**Comment by BastiaanOlij** [comment]
This has been fixed upstream: https://github.com/GodotVR/godot_openxr/pull/163
And merged into master but not yet officially released.

**Comment by Malcolmnixon** [comment]
This has been fixed with godot-openxr 1.2.0 and godot-xr-tools 2.3.0
