### ISSUE TITLE
Default Setup getting an error

### ISSUE THREAD

**Issue by amazingmation** [GodotVR/godot-xr-tools#570]
I set it up like I normally do and it just doesn't work. I haven't done anything differently than before. I did the exact same thing yesterday and it worked just fine. Now I am getting the error : "Error at(435. 25): Identifier "XRToolsUserSettings" not declared in the current scope." on the line " var player_height = XRToolsUserSettings.player_height * XRServer.world_scale". I haven't change anything in the script. This is the default script. It should automatically add the player body to the XROrigin3D and it doesn't, while it did yesterday just fine. I am not sure what exactly is wrong.
![image](https://github.com/GodotVR/godot-xr-tools/assets/121243156/a2439205-ca32-4eac-ac0a-aa94dd83e051)
![image](https://github.com/GodotVR/godot-xr-tools/assets/121243156/2d023b0f-a1fb-4c32-92d5-d9de205ca419)
![image](https://github.com/GodotVR/godot-xr-tools/assets/121243156/0a26f468-2b6e-4db1-971a-538679bc6bf1)

**Comment by Malcolmnixon** [comment]
Godot usually needs one restart after importing a large amount of gdscript code to resolve all the classes. Godot 4.2 is getting much better at resolving on first scan; but it's still not perfect.

Does this happen if you quit and reload the project?

**Comment by amazingmation** [comment]
> Godot usually needs one restart after importing a large amount of gdscript code to resolve all the classes. Godot 4.2 is getting much better at resolving on first scan; but it's still not perfect.
> 
> Does this happen if you quit and reload the project?

Yes it does happen even after a restart. As I said it was working fine the day before and then it broke. I tried redoing it in a new game and it is still broken even after a restart of godot.

**Comment by Malcolmnixon** [comment]
Is it possible the Godot XR Tools plugin isn't enabled?
![image](https://github.com/GodotVR/godot-xr-tools/assets/1863707/ed973a13-bbef-421d-9e79-b8fb924fd71c)

With that enabled all the types should be working for you.

**Comment by amazingmation** [comment]
Thanks. Apparently I did forget to turn on the plugin. :)

**Comment by amazingmation** [comment]
Plugin wasn't enabled :)
