### ISSUE TITLE
There is no 'add_animation' function in AnimationPlayer any all

### ISSUE THREAD

**Issue by SmallKi** [GodotVR/godot-xr-tools#589]
In res://addons/godot-xr-tools/hands/hand.gd. 
![image](https://github.com/GodotVR/godot-xr-tools/assets/37371850/779772a3-2659-47c6-8506-d5e314a16ea6)

Here try to add animation to AnimationPlayer, but this func is deprecated in 4.2. 
Instead, you have to get animation library first and then add animation to the library. 
The same to add "close pose" after this.

**Comment by Malcolmnixon** [comment]
In reviewing the code it may be beneficial for the hands to:
1. Build a "dynamic" AnimationLibrary at runtime
2. Add the "dynamic" AnimationLibrary to the AnimationTree
3. Modify the "dynamic" AnimationLibrary when switching pose animations
