### ISSUE TITLE
grab points don't work when a pickable object is a parent of another pickable object

### ISSUE THREAD

**Issue by Lewis-glasgow** [GodotVR/godot-xr-tools#617]
![image](https://github.com/GodotVR/godot-xr-tools/assets/85359233/d86b8822-1540-45be-8286-77058afe88a9)

when attempting to hold a pickable object that has a parent of another pickable object, it behaves as if there is no grab points at all. it could be a case of misconfigured nodes but i have tried everything, adding the child pickable node to its own scene works perfecly fine but not in its current setup

**Comment by DigitalN8m4r3** [comment]
same as my discord message, lookup the demo scene of the pickables, it contains a sniper rifle which is setup to use a interactable slider, once u grab it, your hand snaps to it and u can pull it.
this issue can be closed

**Comment by Lewis-glasgow** [comment]
Found the issue, super() needs to be called in the reddit function due to godot 4
