### ISSUE TITLE
Jolt physics brakes climbing

### ISSUE THREAD

**Issue by Lewis-glasgow** [GodotVR/godot-xr-tools#632]
When default physics are used the climbing works as expected but switching to jolt makes nothing happen when trying to climb, all other types of movement works as intended when using jolt.

**Comment by Purplooo** [comment]
I found out after some testing that the way XRToolsFunctionPickup works is by detecting if the body its colliding with has the method "pick_up" in its script, it detects rigid bodys and character bodys just fine. Except for the static body 3D, this is disabled by default, to enable go to project_settings>Jolt>Collisions>Areas_Detect_Static_Bodys and enable it.

Also remember to use advanced settings to see the option

Hope this helps

**Comment by QuinnLeavitt** [comment]
Added some [documentation](https://github.com/GodotVR/godot-xr-tools/pull/644) to address this issue.
