### ISSUE TITLE
Godot 4.3: Vignette unusable

### ISSUE THREAD

**Issue by ToxicCrack** [GodotVR/godot-xr-tools#668]
Hi, i updated my project from Godot 4.2.2 to 4.3. In 4.3, the vignette is just flickering over the entire viewport, even without moving ingame. Any ideas what causes this?

**Comment by Malcolmnixon** [comment]
Confirmed - I suspect it's to do with the [Reverse-Z](https://godotengine.org/article/introducing-reverse-z/) change in Godot shaders and how the coordinates are calculated; however I'm pretty weak in Shader-Fu. This will probably require @BastiaanOlij to get working.

**Comment by BastiaanOlij** [comment]
Wow, there's been a bug in there for some time. Seeing we have 4.3 as a minimum now I think we should just adjust it for reverse-z and stick with that.

Two fixes are need:
1. `v.xy += eye.xy / eye.z;` should be `v.xy += eye.xy / eye.w;`
2. `POSITION = vec4(v, 1.0);` should be `POSITION = vec4(v.xy, 1.0, 1.0);`

I think those should make the vignette work again.
