### ISSUE TITLE
Viewport2Din3D documentation has incorrect statement about how to use nested scene

### ISSUE THREAD

**Issue by Meorge** [GodotVR/godot-xr-tools#672]
The documentation for Viewport2Din3D (on https://godotvr.github.io/godot-xr-tools/docs/pointer/) states the following:
> The 2D scene to display on the viewport, alternatively you can enable editable children and add this as a child to the “Screen” node

I just tested this and found the 2D scene should not be added to the "Screen" node, but rather the "Viewport" node. This makes sense in retrospect, since the viewport should be rendering the 2D scene, with the "Screen" node displaying the result of the viewport's rendering.

**Comment by Malcolmnixon** [comment]
Documentation fix merged and live on [website](https://godotvr.github.io/godot-xr-tools/docs/pointer/)
