### ISSUE TITLE
OpenXRCompositionLayer not working with staging

### ISSUE THREAD

**Issue by arassec** [GodotVR/godot-xr-tools#680]
Hi,

i tested the OpenXRCompositionLayer from Godot 4.3 and it seems to not work with the "Staging" base scenes from the XR Tools.
The layer is shown in the editor and there are no errors, but the UI simply is not rendered in XR (tested with a Pico 4).

The following versions were tested:
- Godot: 4.3
- XR-Tools: 4.3.3 and 4.4.0-dev1

Test setup was a basic scene based on the xr_composition_layers demo:
![xrtools-staging-composition-layer](https://github.com/user-attachments/assets/41bfc357-9f9a-46bf-a265-a663f5dfffb7)

Without scene inheritance the UI is rendered fine.

**Comment by surreal6** [comment]
Hi. do you think this is the same issue?

https://github.com/godotengine/godot/issues/96645

compositionLayer is not implemented in xr tools, but in the main engine. Maybe you can confirm you have the same problem there.

**Comment by arassec** [comment]
Hi,
i think you are right. I tested you example and see the same behavior.

This seemed to be a problem of "scene inheritance with staging", but it has indeed nothing to do with the XR-Tools staging scenes.

I will close this bug and comment on yours!
