### ISSUE TITLE
How to add new hand poses?

### ISSUE THREAD

**Issue by LeandroSQ** [GodotVR/godot-xr-tools#688]
First of all, thank you for all the amazing work, I'm loving the experience with VR in Godot so far!

I wonder how to add custom hand poses, as the default ones don't really seem to fit correctly the object I'm introducing to my game.

**Comment by DigitalN8m4r3** [comment]
links are inside the Readme, this is one way and it is for now valid for the currentxr tools even if the Videos are made for godot 3.5, the same process is used in godot 4

https://m.youtube.com/playlist?list=PLBpYNPEE9RKiB7Rnn1tDpMO5wQEG0WnUt

**Comment by LeandroSQ** [comment]
Awesome video reference, thank you :)

Unfortunately I was not able to load the keyframes:
![image](https://github.com/user-attachments/assets/31b24a49-1746-44ad-a491-4c1c77b472fd)

What I've is different noticed:
- `gltf embedded export` is not available on blender 4.2.2
- `import -> storage` has moved on Godot 4, I tried using `Import -> Advanced -> Actions -> Set Animation Save Paths` which got me a `.res` file, but when opening it up on the animation timeline... no keyframes there

**Comment by LeandroSQ** [comment]
My Blender export 
![image](https://github.com/user-attachments/assets/11abd466-d6f5-461e-9557-9217286cd1a5)
All keyframes and armature are there, if I reload the .blend file it works flawlessly
![image](https://github.com/user-attachments/assets/ce6fc72f-983f-42cf-ab61-38aca2dba0ab)

**Comment by LeandroSQ** [comment]
[Archive.zip](https://github.com/user-attachments/files/17428196/Archive.zip)
In case it helps, I've included my files here ^

**Comment by DigitalN8m4r3** [comment]
[camera_hold_animations.zip](https://github.com/user-attachments/files/17429789/camera_hold_animations.zip)
here is a fixed version for you, however it wont work for the left hand but you should now be able to do this on your own

@LeandroSQ 

when exporting, make sure to select the armature in object mode, before you export make sure to set the Material export to - No export
![grafik](https://github.com/user-attachments/assets/aece5006-a90d-4f57-a5f4-2657ca1a4b81)

inside Godot,
![grafik](https://github.com/user-attachments/assets/50b21c0c-0172-4ed4-8139-fa47f5cd5c5d)
![grafik](https://github.com/user-attachments/assets/c881014e-fd8f-4e87-8a8b-7d7a896c6ae2)
![grafik](https://github.com/user-attachments/assets/043337dd-0e36-46a5-89e1-a454f4d20ad8)
![grafik](https://github.com/user-attachments/assets/1ba1865e-80be-45cf-bcad-e3c9e3221ccd)

now open any existing right hand scene and go to animationplayer
![grafik](https://github.com/user-attachments/assets/0afdc760-e4ca-48aa-8fa6-584c4ef38293)
and now create a new animation library like so
![grafik](https://github.com/user-attachments/assets/b8b66c06-8aba-415b-9032-b993d0cb1918)

upon creating the library just add your animation pose, it got automaticly created prior when we did the reimport
![grafik](https://github.com/user-attachments/assets/e6e206ae-05a5-45a7-a3dc-1b30bfdac668)
and here save the newly created library, thats all there is, you should now be able to set the pose

**Comment by LeandroSQ** [comment]
This worked, thank you so much!
