### ISSUE TITLE
Whats the point of this line of code? (hand_physics_bone.gd)

### ISSUE THREAD

**Issue by TrevorBlythe** [GodotVR/godot-xr-tools#689]
Why are you doing this
```
# This method teleports the physics-bone to the skeletal-bone.
func _teleport_bone() -> void:
	# Get the bone transform
	var bone_xform := _skeletal_bone.global_transform
	
        #Set the bone position
	_physics_bone.global_transform = Transform3D(
		Basis(bone_xform.basis.get_rotation_quaternion()),
		bone_xform.origin)
```

Why dont you just set the transforms to be the same directly? like this ->
```
	# Set the bone position
	_physics_bone.global_transform = _skeletal_bone.global_transform
```
I tried it and nothing changed in my game so I guess it worked?

**Comment by ProPuke** [comment]
They're avoiding differences in _scale_. Their code only applies the rotation and translation,  but not scale. So in cases where a bone is stretched or squished the physics bone will still be uniform scale.

I don't believe physics bones support non-uniform scales, so this is probably to avoid spamming the console with warnings when that happens.

**Comment by TrevorBlythe** [comment]
alright my bad
