### ISSUE TITLE
Pointer event not working?

### ISSUE THREAD

**Issue by kmare** [GodotVR/godot-xr-tools#74]
I've tried setting up a simple scene where I simply want to trigger an event when clicking on an object.
I've followed the instructions from the README, where I should just implement the _on_pointer_pressed and _on_pointer_released functions on the StaticBody node.
That doesn't seem to do anything though.

I've tried the teleport function and it works fine.
Am I missing something or is it a bug?
I'm using the godot-openxr plugin 1.1.1 and godot-xr-tools 2.2.0.

Thank you!

**Comment by Malcolmnixon** [comment]
I haven't played with this yet, but I just took a look at the code. The Function_pointer object fires the following **signals** at the object being pointed at:
- pointer_entered()
- pointer_exited()
- pointer_moved(from, to)
- pointer_pressed(at)
- pointer_released(at)

If you want to handle these signals, I believe you need to:
1. Derive your script from XRToolsInteractableBody so you define these signals
2. Use the signal connection GUI to connect the events you're interested in to functions in your script.

You would probably create a script looking something like:
```
class_name MyPointerHandler
extends XRToolsInteractableBody

## Function invoked by the 'pointer_pressed' signal
func _on_pointer_pressed(at):
    pass

## Function invoked by the 'pointer_released' signal
func _on_pointer_released(at):
    pass
```

Then you could:
- Add the script to the StaticBody
- Connect the 'pointer_pressed' signal connected to the _on_pointer_pressed function in your script
- Connect the 'pointer_released' signal connected to the _on_pointer_released function in your script

**Comment by kmare** [comment]
wow @Malcolmnixon, thank you so much! I'm quite experienced in programming, but I'm fairly new with Godot. Wasn't aware of how to connect signals etc, so I actually learned quite a few things from your description!
Would be cool if that could be included in the documentation as it might help others (newbies like myself!). 
Thanks again!

**Comment by Malcolmnixon** [comment]
No problem, I know Bastiaan is working on the documentation when he gets a chance. There's also the Godot discord server which has a specific XR help area if you have questions. Good luck!
