### ISSUE TITLE
Picked up objects do not have a signal for dropped

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#75]
The Object_pickable script fires a 'picked_up' signal when the object is picked up, but has no corresponding signal for when the object is dropped. The let_go function could be modified to fire a new 'dropped' signal.

It would also be beneficial to add an "action" signal for when the picked object has its action invoked by the associated controller action button.

**Comment by BastiaanOlij** [comment]
I'm surprised I didn't add this, agree with this.

**Comment by BastiaanOlij** [comment]
Merged and thanks :)
