### ISSUE TITLE
Object_pickable reports get_node error for PickupCenter

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#76]
The Object_pickable script makes use of an optional "PickupCenter" child node, but only when the "reset_transform_on_pickup" is enabled. The _get_configuration_warning only reports a warning for a missing "PickupCenter" if the "reset_transform_on_pickup" flag is enabled.

The _ready() function is written with:
```
    center_pickup_on_node = get_node("PickupCenter")
```

Unfortunately the get_node reports an error if the node cannot be found. To prevent the error from cluttering the debugger, this could be changed to either:
```
    center_pickup_on_node = get_node_or_null("PickupCenter")
```
or possibly:
```
    if reset_transform_on_pickup:
        center_pickup_on_node = get_node("PickupCenter")
```

**Comment by BastiaanOlij** [comment]
I prefer the get_node_or_null to silence it provided we check if center_pickup_on_node is set before we use it
