### ISSUE TITLE
Direct Movement snap turn should be possible on opposite controller

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#78]
It's more common to allow the joystick to strafe left and right as well as forwards and backwards, and put the snap turn on left-right the opposite controller.  How is this system going to be able to capture commands from the other controller?

**Comment by Malcolmnixon** [comment]
You should be able to achieve this using two direct movement controllers. The configuration I tend to use is:
 - Direct Movement under Left Controller configured for move/strafe
 - Direct Movement under Right Controller configured for move/rotate (set for smooth or snap rotation as preferred)

**Comment by goatchurchprime** [comment]
Just spotted the move and strafe option.  Trying out.  

Can't get any of the other buttons to work, though. (grip, fly, teleport, etc)
