### ISSUE TITLE
4.0-dev branch will soon move to master now that Godot 4.0 is out!

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot-xr-tools#82]
The `4.0-dev` contains the Work in Progress conversion of Godot-XR-Tools to Godot 4. 
Changes made to `master` should be ported to the `4.0-dev` branch as well as these will deviate elsewise.

**Comment by BastiaanOlij** [comment]
Now that Godot 4.0 has been officially released, we will soon be updating master and create a 3.x branch to keep pushing out fixes and improvements to the Godot 3.x version.

**Comment by DigitalN8m4r3** [comment]
regarding that, got a pr up that adds the latest master stuff to the 4.0 dev branch
#406 

besides the already mentioned stuff from the master branch, it contains the backpack inventory as well as a snap_zone fix regarding the tool annotation (those are not yet merged in the master branch/ need review)

**Comment by pietru2004** [comment]
@DigitalN8m4r3 backpack inventory ? Is it related to this https://github.com/GodotVR/godot-xr-tools/issues/351?

**Comment by DigitalN8m4r3** [comment]
> @DigitalN8m4r3 backpack inventory ? Is it related to this #351 and #366?

Not quiet as my inventory uses what is already there in the form of the snap zones with a enhancement of being able to carry the backpack around and if wished drop it, it would return after set time passed to your shoulder

anyways, this pr is closed
any further discussions about this can be held in the godot xr discord

**Comment by BastiaanOlij** [comment]
We need to get a better process in place dealing with features that span both versions, especially with the issues we've been having with PRs arbitrarily updating import files or touching parts of the code that should be in their own PRs.

**Comment by BastiaanOlij** [comment]
Anyway, I'm closing this issue for a brand new documentation issue :)
