### ISSUE TITLE
Keyboard controlled VR simulator

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#93]
This is essential for efficient debugging so you can perform quick iterative tests against the parts of the game under development without needing to boot up the headset.  

The OQ_Toolkit had this feature on by default when there was no VR interface present and overlayed the control instructions onto the screen.
https://github.com/NeoSpark314/godot_oculus_quest_toolkit/blob/master/OQ_Toolkit/OQ_ARVROrigin/scripts/Feature_VRSimulator.gd

It would be great if the keyboard controls were to map onto the VR controls (eg WASD and Shift-WASD for left and right controller joysticks) so we didn't need to implement motions in two different ways.

**Comment by BastiaanOlij** [comment]
Hmmm, needs to be optional for us, OQ_Toolkit targeted Quest with then simulating on desktop if you wanted to test. We're trying to keep this toolkit platform agnostic and it's very possible the setup is used for an optional VR situation where when you start without VR, you want the game to work in desktop mode that isn't mimicking the standard 2 controller setup (think of flight sims, driving sims, etc)

**Comment by goatchurchprime** [comment]
Yes.  There's two distinct purposes for this interface.  

(a) Simulating the VR button interactions to some limited extent from the keyboard to make it easier to debug elements of the VR code without requiring use of the VR headset for every single iteration.

(b) Driving your app through a keyboard+mouse interface that is optimized for this interface (eg with additional hot-keys for menu selecting).  

Ideally these different purposes to have an overlapping implementation.

**Comment by BastiaanOlij** [comment]
There are two different scenarios here.

1) For mixed games where you want to play in non-VR or VR, we're moving to a characterbody based approach in a version of XR Tools in the near future which will make this much easier without needing us to do some sort of XR to non-XR compatibility layer.

2) For testing VR games without needing to use your headset, we've had the stance for awhile that it's better to use a tool that implements this capability as an OpenXR runtime so you're really testing your game, then using an alternative game stack.

There are now a few options to do this:
- Monado has a stand along test setup
- Meta has their simulator: https://developer.oculus.com/blog/boost-iteration-efficiency-meta-xr-simulator-experimental/ (works with Godot too, not just Unity)
- Varjo has their simulator you can download and use

Closing this issue.

**Comment by goatchurchprime** [comment]
There's also this one, which seems to work https://github.com/goatchurchprime/godot-vr-simulator
(Though not able to operate dropdown boxes in a viewport2d_in_3d yet.)
