### ISSUE TITLE
Removing scenes for functions and classes

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot-xr-tools#99]
Right now most of the features in XR Tools need to be added through subscenes. That makes a lot of sense as for many we need a handful of objects properly configured to make the function usable.

However we also define all classes with `class_name` which makes it possible to see them in the node tree and just add the node. If you do this, you get a node of the correct type, with the script attached, but it doesn't use the related scene.

Most of the scenes are really simple with just a handful of objects. It is fully possible to add the needed nodes in the `_ready` function of a script and remove the need to have the scenes.

Obviously this is something worth discussing whether we want to do this and to what type of classes to restrict this too. For instance, the scenes meant to be inherited should remain scenes, but we could fully remove the function scenes for instance.

Also this would be a serious breaking change and maybe something we should consider only for Godot 4.

**Comment by Malcolmnixon** [comment]
Just talked with a user that's trying to position their player in the scene, and the player leaves a bunch of objects behind. These are all the helper objects under the movement functions (the wind sensor area), and as the MovementProvider isn't a Spatial node, the movement of the parent does nothing for the child.

Switching to script-generated helper objects would fix this problem - as would making MovementProvider extend from Spatial.

**Comment by BastiaanOlij** [comment]
After discussing with Malcolm, we're slowly changing this over where we can, there is no point in keeping this issue open.
